/**
 * Seeds products for all expanded ingredients (3 tiers each).
 * Run: npm run seed:products:expanded
 * ASINs are placeholders — replace with verified ASINs before launch.
 */

import { Surreal, RecordId } from 'surrealdb';

interface ProductSeed {
  id: string;
  asin: string;
  name: string;
  slug: string;
  brand_name: string;
  brand_website: string;
  tier: 'aspiration' | 'rational' | 'economic';
  rrp: number;
  rrp_currency: string;
  certifications: string[];
  packet_text: string;
  link_official?: string;
  link_generic_ingredient: string;
  ingredient_id: string;
  dose_per_serving: string;
  unit: string;
  form: string;
}

const PRODUCTS: ProductSeed[] = [

  // ─── L-THEANINE ────────────────────────────────────────────────────────────
  {
    id: 'product:thorne-l-theanine',
    asin: 'B0019LTMTE',
    name: 'Thorne L-Theanine',
    slug: 'thorne-l-theanine',
    brand_name: 'Thorne',
    brand_website: 'https://www.thorne.com',
    tier: 'aspiration',
    rrp: 24.99, rrp_currency: 'GBP',
    certifications: ['NSF Certified for Sport', 'GMP'],
    packet_text: 'L-Theanine 200mg. 90 capsules. As found in green tea. Take 1 capsule daily or as directed.',
    link_official: 'https://www.thorne.com/products/dp/l-theanine',
    link_generic_ingredient: 'L-Theanine supplement',
    ingredient_id: 'ingredient:l-theanine',
    dose_per_serving: '200', unit: 'mg', form: 'Free-form L-Theanine',
  },
  {
    id: 'product:solgar-l-theanine',
    asin: 'B001GAOGM8',
    name: 'Solgar L-Theanine',
    slug: 'solgar-l-theanine',
    brand_name: 'Solgar',
    brand_website: 'https://www.solgar.com',
    tier: 'rational',
    rrp: 18.99, rrp_currency: 'GBP',
    certifications: ['Kosher', 'GMP'],
    packet_text: 'L-Theanine 150mg. 60 vegetable capsules. Take 1-2 capsules daily.',
    link_generic_ingredient: 'L-Theanine supplement',
    ingredient_id: 'ingredient:l-theanine',
    dose_per_serving: '150', unit: 'mg', form: 'Free-form L-Theanine',
  },
  {
    id: 'product:bulk-l-theanine-capsules',
    asin: 'B01AJUAPDY',
    name: 'Bulk L-Theanine Capsules',
    slug: 'bulk-l-theanine-capsules',
    brand_name: 'Bulk',
    brand_website: 'https://www.bulk.com',
    tier: 'economic',
    rrp: 9.99, rrp_currency: 'GBP',
    certifications: [],
    packet_text: 'L-Theanine 200mg. 90 capsules. Take 1 capsule daily.',
    link_generic_ingredient: 'L-Theanine supplement',
    ingredient_id: 'ingredient:l-theanine',
    dose_per_serving: '200', unit: 'mg', form: 'Free-form L-Theanine',
  },

  // ─── 5-HTP ─────────────────────────────────────────────────────────────────
  {
    id: 'product:natrol-5htp-time-release',
    asin: 'B00020IN08',
    name: 'Natrol 5-HTP Time Release',
    slug: 'natrol-5htp-time-release',
    brand_name: 'Natrol',
    brand_website: 'https://www.natrol.com',
    tier: 'aspiration',
    rrp: 19.99, rrp_currency: 'GBP',
    certifications: ['GMP'],
    packet_text: '5-HTP 100mg. Time release formula. 45 tablets. Derived from Griffonia simplicifolia seed. Take 1 tablet daily with food.',
    link_generic_ingredient: '5-HTP supplement Griffonia simplicifolia',
    ingredient_id: 'ingredient:5-htp',
    dose_per_serving: '100', unit: 'mg', form: 'Time-release tablet',
  },
  {
    id: 'product:solgar-5htp',
    asin: 'B0013OXC3C',
    name: 'Solgar 5-HTP',
    slug: 'solgar-5htp',
    brand_name: 'Solgar',
    brand_website: 'https://www.solgar.com',
    tier: 'rational',
    rrp: 16.99, rrp_currency: 'GBP',
    certifications: ['Kosher', 'GMP'],
    packet_text: '5-HTP 100mg. 90 vegetable capsules. From Griffonia simplicifolia seed. Take 1 capsule 2-3 times daily between meals.',
    link_generic_ingredient: '5-HTP supplement Griffonia simplicifolia',
    ingredient_id: 'ingredient:5-htp',
    dose_per_serving: '100', unit: 'mg', form: 'Vegetable capsule',
  },
  {
    id: 'product:nowfoods-5htp',
    asin: 'B001GAOGM0',
    name: 'NOW Foods 5-HTP',
    slug: 'nowfoods-5htp',
    brand_name: 'NOW Foods',
    brand_website: 'https://www.nowfoods.com',
    tier: 'economic',
    rrp: 11.99, rrp_currency: 'GBP',
    certifications: ['GMP', 'Non-GMO'],
    packet_text: '5-HTP 100mg. 120 veg capsules. From Griffonia simplicifolia. Take 1-2 capsules between meals.',
    link_generic_ingredient: '5-HTP supplement Griffonia simplicifolia',
    ingredient_id: 'ingredient:5-htp',
    dose_per_serving: '100', unit: 'mg', form: 'Vegetable capsule',
  },

  // ─── BACOPA MONNIERI ───────────────────────────────────────────────────────
  {
    id: 'product:double-wood-bacopa',
    asin: 'B00XTXOZO8',
    name: 'Double Wood Bacopa Monnieri',
    slug: 'double-wood-bacopa',
    brand_name: 'Double Wood Supplements',
    brand_website: 'https://www.doublewoodsupplements.com',
    tier: 'aspiration',
    rrp: 19.99, rrp_currency: 'GBP',
    certifications: ['GMP', 'Third-party tested'],
    packet_text: 'Bacopa Monnieri Extract 300mg (45% bacosides). 60 capsules. Take 1 capsule twice daily with food.',
    link_generic_ingredient: 'Bacopa monnieri brahmi extract',
    ingredient_id: 'ingredient:bacopa-monnieri',
    dose_per_serving: '300', unit: 'mg', form: '45% Bacosides Extract',
  },
  {
    id: 'product:jarrow-bacopa',
    asin: 'B0013OQKPA',
    name: 'Jarrow Formulas Bacopa',
    slug: 'jarrow-bacopa',
    brand_name: 'Jarrow Formulas',
    brand_website: 'https://www.jarrow.com',
    tier: 'rational',
    rrp: 14.99, rrp_currency: 'GBP',
    certifications: ['GMP'],
    packet_text: 'Bacopa Monnieri 320mg (Mega-Brahmi standardised extract). 60 tablets. Take 1 tablet daily with a meal.',
    link_generic_ingredient: 'Bacopa monnieri brahmi extract',
    ingredient_id: 'ingredient:bacopa-monnieri',
    dose_per_serving: '320', unit: 'mg', form: 'Standardised Extract',
  },
  {
    id: 'product:bulk-bacopa-extract',
    asin: 'B01N0GLNHK',
    name: 'Bulk Bacopa Extract Capsules',
    slug: 'bulk-bacopa-extract',
    brand_name: 'Bulk',
    brand_website: 'https://www.bulk.com',
    tier: 'economic',
    rrp: 8.99, rrp_currency: 'GBP',
    certifications: [],
    packet_text: 'Bacopa Monnieri Extract 300mg (50% Bacosides). 90 capsules. Take 1 capsule with food.',
    link_generic_ingredient: 'Bacopa monnieri brahmi extract',
    ingredient_id: 'ingredient:bacopa-monnieri',
    dose_per_serving: '300', unit: 'mg', form: 'Standardised Extract',
  },

  // ─── ALPHA-GPC ─────────────────────────────────────────────────────────────
  {
    id: 'product:jarrow-alpha-gpc',
    asin: 'B00150Z1FK',
    name: 'Jarrow Formulas Alpha GPC',
    slug: 'jarrow-alpha-gpc',
    brand_name: 'Jarrow Formulas',
    brand_website: 'https://www.jarrow.com',
    tier: 'aspiration',
    rrp: 29.99, rrp_currency: 'GBP',
    certifications: ['GMP'],
    packet_text: 'Alpha GPC 300mg. 60 capsules. Each capsule provides 300mg Alpha-glycerylphosphorylcholine. Take 1 capsule 1-3 times daily.',
    link_generic_ingredient: 'Alpha-GPC choline supplement',
    ingredient_id: 'ingredient:alpha-gpc',
    dose_per_serving: '300', unit: 'mg', form: 'Alpha-GPC',
  },
  {
    id: 'product:solgar-alpha-gpc',
    asin: 'B0015AY0N8',
    name: 'Solgar Alpha-GPC',
    slug: 'solgar-alpha-gpc',
    brand_name: 'Solgar',
    brand_website: 'https://www.solgar.com',
    tier: 'rational',
    rrp: 22.99, rrp_currency: 'GBP',
    certifications: ['Kosher', 'GMP'],
    packet_text: 'Alpha GPC (from soy lecithin) 200mg. 60 vegetable capsules. Take 1 capsule daily.',
    link_generic_ingredient: 'Alpha-GPC choline supplement',
    ingredient_id: 'ingredient:alpha-gpc',
    dose_per_serving: '200', unit: 'mg', form: 'Soy-derived Alpha-GPC',
  },
  {
    id: 'product:nowfoods-alpha-gpc',
    asin: 'B001GAOCUI',
    name: 'NOW Foods Alpha GPC',
    slug: 'nowfoods-alpha-gpc',
    brand_name: 'NOW Foods',
    brand_website: 'https://www.nowfoods.com',
    tier: 'economic',
    rrp: 16.99, rrp_currency: 'GBP',
    certifications: ['GMP', 'Non-GMO'],
    packet_text: 'Alpha GPC 300mg. 60 veg capsules. Take 1 capsule daily.',
    link_generic_ingredient: 'Alpha-GPC choline supplement',
    ingredient_id: 'ingredient:alpha-gpc',
    dose_per_serving: '300', unit: 'mg', form: 'Alpha-GPC',
  },

  // ─── PHOSPHATIDYLSERINE ────────────────────────────────────────────────────
  {
    id: 'product:jarrow-ps-100',
    asin: 'B001GA0FW0',
    name: 'Jarrow Formulas Phosphatidylserine PS-100',
    slug: 'jarrow-ps-100',
    brand_name: 'Jarrow Formulas',
    brand_website: 'https://www.jarrow.com',
    tier: 'aspiration',
    rrp: 24.99, rrp_currency: 'GBP',
    certifications: ['GMP'],
    packet_text: 'Phosphatidylserine (from soy lecithin) 100mg. 60 softgels. Take 1-3 softgels daily with meals.',
    link_generic_ingredient: 'phosphatidylserine supplement soy',
    ingredient_id: 'ingredient:phosphatidylserine',
    dose_per_serving: '100', unit: 'mg', form: 'Soy-derived PS',
  },
  {
    id: 'product:nowfoods-phosphatidylserine',
    asin: 'B0019LTMWU',
    name: 'NOW Foods Phosphatidylserine',
    slug: 'nowfoods-phosphatidylserine',
    brand_name: 'NOW Foods',
    brand_website: 'https://www.nowfoods.com',
    tier: 'rational',
    rrp: 18.99, rrp_currency: 'GBP',
    certifications: ['GMP', 'Non-GMO'],
    packet_text: 'Phosphatidylserine 100mg. 120 softgels. Take 1-3 softgels daily with meals.',
    link_generic_ingredient: 'phosphatidylserine supplement soy',
    ingredient_id: 'ingredient:phosphatidylserine',
    dose_per_serving: '100', unit: 'mg', form: 'Soy-derived PS',
  },
  {
    id: 'product:solgar-phosphatidylserine',
    asin: 'B001GAOGMK',
    name: 'Solgar Phosphatidylserine',
    slug: 'solgar-phosphatidylserine',
    brand_name: 'Solgar',
    brand_website: 'https://www.solgar.com',
    tier: 'economic',
    rrp: 14.99, rrp_currency: 'GBP',
    certifications: ['Kosher', 'GMP'],
    packet_text: 'Phosphatidylserine (from soy) 100mg. 60 vegetable capsules.',
    link_generic_ingredient: 'phosphatidylserine supplement soy',
    ingredient_id: 'ingredient:phosphatidylserine',
    dose_per_serving: '100', unit: 'mg', form: 'Soy-derived PS',
  },

  // ─── NAC ────────────────────────────────────────────────────────────────────
  {
    id: 'product:thorne-nac',
    asin: 'B001GA0G6E',
    name: 'Thorne N-Acetylcysteine',
    slug: 'thorne-nac',
    brand_name: 'Thorne',
    brand_website: 'https://www.thorne.com',
    tier: 'aspiration',
    rrp: 22.99, rrp_currency: 'GBP',
    certifications: ['NSF Certified for Sport', 'GMP'],
    packet_text: 'N-Acetylcysteine 500mg. 90 capsules. Take 1-3 capsules daily.',
    link_official: 'https://www.thorne.com/products/dp/nac',
    link_generic_ingredient: 'N-Acetylcysteine NAC supplement',
    ingredient_id: 'ingredient:nac',
    dose_per_serving: '500', unit: 'mg', form: 'NAC capsule',
  },
  {
    id: 'product:nowfoods-nac',
    asin: 'B0013OWN5Q',
    name: 'NOW Foods N-Acetyl Cysteine',
    slug: 'nowfoods-nac',
    brand_name: 'NOW Foods',
    brand_website: 'https://www.nowfoods.com',
    tier: 'rational',
    rrp: 12.99, rrp_currency: 'GBP',
    certifications: ['GMP', 'Non-GMO'],
    packet_text: 'N-Acetyl Cysteine 600mg. 100 veg capsules. Take 1 capsule 2 times daily.',
    link_generic_ingredient: 'N-Acetylcysteine NAC supplement',
    ingredient_id: 'ingredient:nac',
    dose_per_serving: '600', unit: 'mg', form: 'NAC capsule',
  },
  {
    id: 'product:bulk-nac-capsules',
    asin: 'B07CQBF9CM',
    name: 'Bulk N-Acetyl L-Cysteine Capsules',
    slug: 'bulk-nac-capsules',
    brand_name: 'Bulk',
    brand_website: 'https://www.bulk.com',
    tier: 'economic',
    rrp: 8.99, rrp_currency: 'GBP',
    certifications: [],
    packet_text: 'N-Acetyl L-Cysteine (NAC) 500mg. 90 capsules.',
    link_generic_ingredient: 'N-Acetylcysteine NAC supplement',
    ingredient_id: 'ingredient:nac',
    dose_per_serving: '500', unit: 'mg', form: 'NAC capsule',
  },

  // ─── ELDERBERRY ────────────────────────────────────────────────────────────
  {
    id: 'product:sambucol-original',
    asin: 'B001O7YK8C',
    name: 'Sambucol Original Black Elderberry Syrup',
    slug: 'sambucol-original',
    brand_name: 'Sambucol',
    brand_website: 'https://www.sambucolusa.com',
    tier: 'aspiration',
    rrp: 12.99, rrp_currency: 'GBP',
    certifications: ['Informed Sport'],
    packet_text: 'Sambucol Black Elderberry Extract. Each 5ml: Black elderberry extract 3.84g (equivalent to 38.4g fresh elderberries). Take 4 times daily during illness.',
    link_official: 'https://www.sambucol.com',
    link_generic_ingredient: 'black elderberry extract Sambucus nigra',
    ingredient_id: 'ingredient:elderberry',
    dose_per_serving: '3.84', unit: 'g extract', form: 'Liquid syrup',
  },
  {
    id: 'product:natures-sunshine-elderberry',
    asin: 'B01LX5DPKW',
    name: 'Nature\'s Sunshine Elderberry Defense',
    slug: 'natures-sunshine-elderberry',
    brand_name: 'Nature\'s Sunshine',
    brand_website: 'https://www.naturessunshine.com',
    tier: 'rational',
    rrp: 16.99, rrp_currency: 'GBP',
    certifications: ['GMP'],
    packet_text: 'Elderberry Extract 500mg (standardised). 60 capsules. Take 1-2 capsules daily.',
    link_generic_ingredient: 'black elderberry extract Sambucus nigra',
    ingredient_id: 'ingredient:elderberry',
    dose_per_serving: '500', unit: 'mg', form: 'Standardised extract capsule',
  },
  {
    id: 'product:bulk-elderberry-capsules',
    asin: 'B07PXHGVV7',
    name: 'Bulk Elderberry Extract Capsules',
    slug: 'bulk-elderberry-capsules',
    brand_name: 'Bulk',
    brand_website: 'https://www.bulk.com',
    tier: 'economic',
    rrp: 7.99, rrp_currency: 'GBP',
    certifications: [],
    packet_text: 'Elderberry Extract 400mg. 90 capsules. Take 1-2 capsules daily.',
    link_generic_ingredient: 'black elderberry extract Sambucus nigra',
    ingredient_id: 'ingredient:elderberry',
    dose_per_serving: '400', unit: 'mg', form: 'Extract capsule',
  },

  // ─── BETA-GLUCAN ───────────────────────────────────────────────────────────
  {
    id: 'product:wellmune-beta-glucan',
    asin: 'B00LQHPZ4I',
    name: 'Wellmune Beta-Glucan 250mg',
    slug: 'wellmune-beta-glucan',
    brand_name: 'Wellmune',
    brand_website: 'https://www.wellmune.com',
    tier: 'aspiration',
    rrp: 22.99, rrp_currency: 'GBP',
    certifications: ['GMP', 'NSF'],
    packet_text: 'Wellmune Beta-1,3/1,6-Glucan 250mg (from Saccharomyces cerevisiae). 60 capsules. Take 1 capsule daily.',
    link_generic_ingredient: 'beta-1,3/1,6-glucan immune supplement',
    ingredient_id: 'ingredient:beta-glucan',
    dose_per_serving: '250', unit: 'mg', form: 'Yeast beta-1,3/1,6-glucan',
  },
  {
    id: 'product:source-naturals-beta-glucan',
    asin: 'B000GFPF04',
    name: 'Source Naturals Beta Glucan',
    slug: 'source-naturals-beta-glucan',
    brand_name: 'Source Naturals',
    brand_website: 'https://www.sourcenaturals.com',
    tier: 'rational',
    rrp: 14.99, rrp_currency: 'GBP',
    certifications: ['GMP'],
    packet_text: 'Beta Glucan 100mg. 30 tablets. Take 1 tablet daily on an empty stomach.',
    link_generic_ingredient: 'beta-glucan immune supplement',
    ingredient_id: 'ingredient:beta-glucan',
    dose_per_serving: '100', unit: 'mg', form: 'Beta-glucan tablet',
  },
  {
    id: 'product:nowfoods-beta-glucan',
    asin: 'B000HJQQ96',
    name: 'NOW Foods Beta-Glucan',
    slug: 'nowfoods-beta-glucan',
    brand_name: 'NOW Foods',
    brand_website: 'https://www.nowfoods.com',
    tier: 'economic',
    rrp: 9.99, rrp_currency: 'GBP',
    certifications: ['GMP', 'Non-GMO'],
    packet_text: 'Beta-Glucan 200mg (from oat fibre). 90 veg capsules. Take 1-2 capsules daily with food.',
    link_generic_ingredient: 'beta-glucan immune supplement',
    ingredient_id: 'ingredient:beta-glucan',
    dose_per_serving: '200', unit: 'mg', form: 'Oat beta-glucan',
  },

  // ─── BOSWELLIA ─────────────────────────────────────────────────────────────
  {
    id: 'product:solgar-boswellia',
    asin: 'B00020INGY',
    name: 'Solgar Boswellia Resin Extract',
    slug: 'solgar-boswellia',
    brand_name: 'Solgar',
    brand_website: 'https://www.solgar.com',
    tier: 'aspiration',
    rrp: 18.99, rrp_currency: 'GBP',
    certifications: ['Kosher', 'GMP'],
    packet_text: 'Boswellia Resin Extract 200mg (65% boswellic acids). 60 vegetable capsules. Take 1 capsule 2 times daily with food.',
    link_generic_ingredient: 'boswellia serrata boswellic acid supplement',
    ingredient_id: 'ingredient:boswellia',
    dose_per_serving: '200', unit: 'mg', form: '65% Boswellic Acids',
  },
  {
    id: 'product:nowfoods-boswellia',
    asin: 'B00020ING2',
    name: 'NOW Foods Boswellia Extract',
    slug: 'nowfoods-boswellia',
    brand_name: 'NOW Foods',
    brand_website: 'https://www.nowfoods.com',
    tier: 'rational',
    rrp: 12.99, rrp_currency: 'GBP',
    certifications: ['GMP', 'Non-GMO'],
    packet_text: 'Boswellia Extract 500mg (60% boswellic acids). 90 veg softgels. Take 1 softgel 2-3 times daily.',
    link_generic_ingredient: 'boswellia serrata boswellic acid supplement',
    ingredient_id: 'ingredient:boswellia',
    dose_per_serving: '500', unit: 'mg', form: '60% Boswellic Acids',
  },
  {
    id: 'product:bulk-boswellia',
    asin: 'B01HLJICRE',
    name: 'Bulk Boswellia Extract Capsules',
    slug: 'bulk-boswellia',
    brand_name: 'Bulk',
    brand_website: 'https://www.bulk.com',
    tier: 'economic',
    rrp: 8.99, rrp_currency: 'GBP',
    certifications: [],
    packet_text: 'Boswellia Serrata Extract 500mg (65% boswellic acids). 90 capsules.',
    link_generic_ingredient: 'boswellia serrata boswellic acid supplement',
    ingredient_id: 'ingredient:boswellia',
    dose_per_serving: '500', unit: 'mg', form: 'Boswellic Acids Extract',
  },

  // ─── QUERCETIN ─────────────────────────────────────────────────────────────
  {
    id: 'product:thorne-quercetin-phytosome',
    asin: 'B0015AY6VM',
    name: 'Thorne Quercetin Phytosome',
    slug: 'thorne-quercetin-phytosome',
    brand_name: 'Thorne',
    brand_website: 'https://www.thorne.com',
    tier: 'aspiration',
    rrp: 34.99, rrp_currency: 'GBP',
    certifications: ['NSF Certified for Sport', 'GMP'],
    packet_text: 'Quercetin Phytosome (quercetin complexed with sunflower lecithin) 250mg. 60 capsules. Enhanced bioavailability formulation.',
    link_official: 'https://www.thorne.com/products/dp/quercetin-phytosome',
    link_generic_ingredient: 'quercetin supplement',
    ingredient_id: 'ingredient:quercetin',
    dose_per_serving: '250', unit: 'mg', form: 'Quercetin Phytosome',
  },
  {
    id: 'product:jarrow-quercetin',
    asin: 'B0013OUY18',
    name: 'Jarrow Formulas Quercetin 500',
    slug: 'jarrow-quercetin',
    brand_name: 'Jarrow Formulas',
    brand_website: 'https://www.jarrow.com',
    tier: 'rational',
    rrp: 14.99, rrp_currency: 'GBP',
    certifications: ['GMP'],
    packet_text: 'Quercetin 500mg. 100 veg capsules. Take 1 capsule 1-2 times daily.',
    link_generic_ingredient: 'quercetin supplement',
    ingredient_id: 'ingredient:quercetin',
    dose_per_serving: '500', unit: 'mg', form: 'Quercetin dihydrate',
  },
  {
    id: 'product:bulk-quercetin',
    asin: 'B01N0AJKJH',
    name: 'Bulk Quercetin Capsules',
    slug: 'bulk-quercetin',
    brand_name: 'Bulk',
    brand_website: 'https://www.bulk.com',
    tier: 'economic',
    rrp: 8.99, rrp_currency: 'GBP',
    certifications: [],
    packet_text: 'Quercetin Dihydrate 500mg. 90 capsules.',
    link_generic_ingredient: 'quercetin supplement',
    ingredient_id: 'ingredient:quercetin',
    dose_per_serving: '500', unit: 'mg', form: 'Quercetin dihydrate',
  },

  // ─── ASTAXANTHIN ───────────────────────────────────────────────────────────
  {
    id: 'product:nutrex-hawaii-bioastin',
    asin: 'B001HTPHAM',
    name: 'Nutrex Hawaii BioAstin Natural Astaxanthin',
    slug: 'nutrex-hawaii-bioastin',
    brand_name: 'Nutrex Hawaii',
    brand_website: 'https://www.nutrex-hawaii.com',
    tier: 'aspiration',
    rrp: 22.99, rrp_currency: 'GBP',
    certifications: ['Non-GMO', 'GMP'],
    packet_text: 'Natural Astaxanthin 12mg (from Haematococcus pluvialis microalgae). 50 softgels. Take 1 softgel daily with a meal containing fat.',
    link_official: 'https://www.nutrex-hawaii.com/bioastin',
    link_generic_ingredient: 'astaxanthin Haematococcus pluvialis supplement',
    ingredient_id: 'ingredient:astaxanthin',
    dose_per_serving: '12', unit: 'mg', form: 'Natural astaxanthin softgel',
  },
  {
    id: 'product:nowfoods-astaxanthin',
    asin: 'B001GA0KM2',
    name: 'NOW Foods Natural Astaxanthin',
    slug: 'nowfoods-astaxanthin',
    brand_name: 'NOW Foods',
    brand_website: 'https://www.nowfoods.com',
    tier: 'rational',
    rrp: 16.99, rrp_currency: 'GBP',
    certifications: ['GMP', 'Non-GMO'],
    packet_text: 'Astaxanthin 4mg (from Haematococcus pluvialis). 90 softgels. Take 1 softgel daily with food.',
    link_generic_ingredient: 'astaxanthin Haematococcus pluvialis supplement',
    ingredient_id: 'ingredient:astaxanthin',
    dose_per_serving: '4', unit: 'mg', form: 'Natural astaxanthin softgel',
  },
  {
    id: 'product:bulk-astaxanthin',
    asin: 'B07Q5SK7GH',
    name: 'Bulk Astaxanthin Capsules',
    slug: 'bulk-astaxanthin',
    brand_name: 'Bulk',
    brand_website: 'https://www.bulk.com',
    tier: 'economic',
    rrp: 9.99, rrp_currency: 'GBP',
    certifications: [],
    packet_text: 'Astaxanthin 4mg (from Haematococcus pluvialis). 60 capsules. Take with fat-containing meal.',
    link_generic_ingredient: 'astaxanthin Haematococcus pluvialis supplement',
    ingredient_id: 'ingredient:astaxanthin',
    dose_per_serving: '4', unit: 'mg', form: 'Astaxanthin capsule',
  },

  // ─── LUTEIN ────────────────────────────────────────────────────────────────
  {
    id: 'product:thorne-lutein',
    asin: 'B0019LTM9G',
    name: 'Thorne Lutein',
    slug: 'thorne-lutein',
    brand_name: 'Thorne',
    brand_website: 'https://www.thorne.com',
    tier: 'aspiration',
    rrp: 28.99, rrp_currency: 'GBP',
    certifications: ['NSF Certified for Sport', 'GMP'],
    packet_text: 'Lutein 20mg + Zeaxanthin 1mg (FloraGLO® lutein from marigold). 90 softgels. Take 1 softgel daily with a meal.',
    link_generic_ingredient: 'lutein zeaxanthin eye health supplement',
    ingredient_id: 'ingredient:lutein',
    dose_per_serving: '20', unit: 'mg', form: 'FloraGLO Lutein + Zeaxanthin',
  },
  {
    id: 'product:solgar-lutein',
    asin: 'B00020IO0Y',
    name: 'Solgar Lutein 20mg',
    slug: 'solgar-lutein',
    brand_name: 'Solgar',
    brand_website: 'https://www.solgar.com',
    tier: 'rational',
    rrp: 16.99, rrp_currency: 'GBP',
    certifications: ['Kosher', 'GMP'],
    packet_text: 'Lutein (FloraGLO®) 20mg with Zeaxanthin 0.8mg. 60 softgels. Take 1 softgel daily with food.',
    link_generic_ingredient: 'lutein zeaxanthin eye health supplement',
    ingredient_id: 'ingredient:lutein',
    dose_per_serving: '20', unit: 'mg', form: 'FloraGLO Lutein + Zeaxanthin',
  },
  {
    id: 'product:nowfoods-lutein',
    asin: 'B001GA0FJ8',
    name: 'NOW Foods Lutein 20mg',
    slug: 'nowfoods-lutein',
    brand_name: 'NOW Foods',
    brand_website: 'https://www.nowfoods.com',
    tier: 'economic',
    rrp: 11.99, rrp_currency: 'GBP',
    certifications: ['GMP', 'Non-GMO'],
    packet_text: 'Lutein 20mg + Zeaxanthin 0.8mg. 90 softgels. Take 1 softgel daily with meals.',
    link_generic_ingredient: 'lutein zeaxanthin eye health supplement',
    ingredient_id: 'ingredient:lutein',
    dose_per_serving: '20', unit: 'mg', form: 'Lutein + Zeaxanthin',
  },

  // ─── SACCHAROMYCES BOULARDII ───────────────────────────────────────────────
  {
    id: 'product:florastor-daily-probiotic',
    asin: 'B000R39SNE',
    name: 'Florastor Daily Probiotic Supplement',
    slug: 'florastor-daily-probiotic',
    brand_name: 'Florastor',
    brand_website: 'https://www.florastor.com',
    tier: 'aspiration',
    rrp: 29.99, rrp_currency: 'GBP',
    certifications: ['GMP'],
    packet_text: 'Saccharomyces boulardii CNCM I-745 250mg. 50 capsules. Viable yeast count: 5 billion at manufacture. Take 2 capsules daily. Can be taken during antibiotic therapy.',
    link_official: 'https://www.florastor.com',
    link_generic_ingredient: 'Saccharomyces boulardii probiotic supplement',
    ingredient_id: 'ingredient:saccharomyces-boulardii',
    dose_per_serving: '250', unit: 'mg', form: 'S. boulardii CNCM I-745',
  },
  {
    id: 'product:optibac-saccharomyces-boulardii',
    asin: 'B00DQVTQEM',
    name: 'Optibac Saccharomyces boulardii',
    slug: 'optibac-saccharomyces-boulardii',
    brand_name: 'Optibac Probiotics',
    brand_website: 'https://www.optibacprobiotics.com',
    tier: 'rational',
    rrp: 19.99, rrp_currency: 'GBP',
    certifications: ['GMP'],
    packet_text: 'Saccharomyces boulardii 5 billion CFU per capsule. 30 capsules. Each capsule: 500mg. Take 1-2 capsules daily.',
    link_official: 'https://www.optibacprobiotics.com',
    link_generic_ingredient: 'Saccharomyces boulardii probiotic supplement',
    ingredient_id: 'ingredient:saccharomyces-boulardii',
    dose_per_serving: '500', unit: 'mg (5 billion CFU)', form: 'S. boulardii capsule',
  },
  {
    id: 'product:bulk-saccharomyces-boulardii',
    asin: 'B08GQXKBLJ',
    name: 'Bulk Saccharomyces Boulardii Capsules',
    slug: 'bulk-saccharomyces-boulardii',
    brand_name: 'Bulk',
    brand_website: 'https://www.bulk.com',
    tier: 'economic',
    rrp: 12.99, rrp_currency: 'GBP',
    certifications: [],
    packet_text: 'Saccharomyces boulardii 5 billion CFU per capsule. 60 capsules.',
    link_generic_ingredient: 'Saccharomyces boulardii probiotic supplement',
    ingredient_id: 'ingredient:saccharomyces-boulardii',
    dose_per_serving: '250', unit: 'mg (5 billion CFU)', form: 'S. boulardii capsule',
  },

  // ─── INOSITOL ──────────────────────────────────────────────────────────────
  {
    id: 'product:thorne-myo-inositol',
    asin: 'B07BNCQ5DM',
    name: 'Thorne Myo-Inositol Powder',
    slug: 'thorne-myo-inositol',
    brand_name: 'Thorne',
    brand_website: 'https://www.thorne.com',
    tier: 'aspiration',
    rrp: 24.99, rrp_currency: 'GBP',
    certifications: ['NSF Certified for Sport', 'GMP'],
    packet_text: 'Myo-Inositol 2g per serving. 400g powder. Take 1 scoop (2g) twice daily. Dissolves in water.',
    link_official: 'https://www.thorne.com/products/dp/myo-inositol',
    link_generic_ingredient: 'myo-inositol supplement powder',
    ingredient_id: 'ingredient:inositol',
    dose_per_serving: '2000', unit: 'mg', form: 'Myo-Inositol powder',
  },
  {
    id: 'product:nowfoods-inositol',
    asin: 'B000GG4N42',
    name: 'NOW Foods Inositol Powder',
    slug: 'nowfoods-inositol',
    brand_name: 'NOW Foods',
    brand_website: 'https://www.nowfoods.com',
    tier: 'rational',
    rrp: 14.99, rrp_currency: 'GBP',
    certifications: ['GMP', 'Non-GMO'],
    packet_text: 'Inositol (myo-inositol) 4g per serving. 227g powder. Take 1 scoop daily in water or juice.',
    link_generic_ingredient: 'myo-inositol supplement powder',
    ingredient_id: 'ingredient:inositol',
    dose_per_serving: '4000', unit: 'mg', form: 'Myo-Inositol powder',
  },
  {
    id: 'product:bulk-myo-inositol',
    asin: 'B01LRU1EDQ',
    name: 'Bulk Myo-Inositol Powder',
    slug: 'bulk-myo-inositol',
    brand_name: 'Bulk',
    brand_website: 'https://www.bulk.com',
    tier: 'economic',
    rrp: 9.99, rrp_currency: 'GBP',
    certifications: [],
    packet_text: 'Myo-Inositol 500g powder. 2g per serving. Unflavoured.',
    link_generic_ingredient: 'myo-inositol supplement powder',
    ingredient_id: 'ingredient:inositol',
    dose_per_serving: '2000', unit: 'mg', form: 'Myo-Inositol powder',
  },

  // ─── SAFFRON ───────────────────────────────────────────────────────────────
  {
    id: 'product:solgar-saffron',
    asin: 'B07BV28YF4',
    name: 'Solgar Saffron Affron',
    slug: 'solgar-saffron',
    brand_name: 'Solgar',
    brand_website: 'https://www.solgar.com',
    tier: 'aspiration',
    rrp: 28.99, rrp_currency: 'GBP',
    certifications: ['Kosher', 'GMP'],
    packet_text: 'Affron Saffron Extract 28mg (standardised Crocus sativus extract). 60 capsules. Each capsule provides 28mg Affron saffron extract standardised to 3.5% Lepticrosalide.',
    link_generic_ingredient: 'saffron extract supplement Crocus sativus',
    ingredient_id: 'ingredient:saffron',
    dose_per_serving: '28', unit: 'mg', form: 'Affron standardised extract',
  },
  {
    id: 'product:naturesplus-saffron',
    asin: 'B07MC4JXKD',
    name: 'NaturesPlus Saffron Extract',
    slug: 'naturesplus-saffron',
    brand_name: 'NaturesPlus',
    brand_website: 'https://www.naturesplus.com',
    tier: 'rational',
    rrp: 18.99, rrp_currency: 'GBP',
    certifications: ['GMP'],
    packet_text: 'Saffron Extract 88.5mg per capsule. 30 capsules. Take 1 capsule daily with food.',
    link_generic_ingredient: 'saffron extract supplement Crocus sativus',
    ingredient_id: 'ingredient:saffron',
    dose_per_serving: '88.5', unit: 'mg', form: 'Saffron extract capsule',
  },
  {
    id: 'product:bulk-saffron-extract',
    asin: 'B08QVYTSHH',
    name: 'Bulk Saffron Extract Capsules',
    slug: 'bulk-saffron-extract',
    brand_name: 'Bulk',
    brand_website: 'https://www.bulk.com',
    tier: 'economic',
    rrp: 9.99, rrp_currency: 'GBP',
    certifications: [],
    packet_text: 'Saffron Extract 30mg per capsule. 90 capsules.',
    link_generic_ingredient: 'saffron extract supplement Crocus sativus',
    ingredient_id: 'ingredient:saffron',
    dose_per_serving: '30', unit: 'mg', form: 'Saffron extract capsule',
  },

  // ─── GYMNEMA SYLVESTRE ─────────────────────────────────────────────────────
  {
    id: 'product:jarrow-gymnema-sylvestre',
    asin: 'B001GAO0TI',
    name: 'Jarrow Formulas Gymnema Sylvestre',
    slug: 'jarrow-gymnema-sylvestre',
    brand_name: 'Jarrow Formulas',
    brand_website: 'https://www.jarrow.com',
    tier: 'aspiration',
    rrp: 16.99, rrp_currency: 'GBP',
    certifications: ['GMP'],
    packet_text: 'Gymnema Sylvestre Extract 400mg (75% gymnemic acids). 100 capsules. Take 1 capsule before each meal.',
    link_generic_ingredient: 'gymnema sylvestre gurmar supplement',
    ingredient_id: 'ingredient:gymnema-sylvestre',
    dose_per_serving: '400', unit: 'mg', form: '75% Gymnemic Acids',
  },
  {
    id: 'product:nowfoods-gymnema',
    asin: 'B001GAOWMY',
    name: 'NOW Foods Gymnema Sylvestre',
    slug: 'nowfoods-gymnema',
    brand_name: 'NOW Foods',
    brand_website: 'https://www.nowfoods.com',
    tier: 'rational',
    rrp: 12.99, rrp_currency: 'GBP',
    certifications: ['GMP', 'Non-GMO'],
    packet_text: 'Gymnema Sylvestre Extract 400mg (25% gymnemic acids). 90 veg capsules. Take 1 capsule 3 times daily before meals.',
    link_generic_ingredient: 'gymnema sylvestre gurmar supplement',
    ingredient_id: 'ingredient:gymnema-sylvestre',
    dose_per_serving: '400', unit: 'mg', form: 'Standardised extract',
  },
  {
    id: 'product:bulk-gymnema',
    asin: 'B07Q3WLTQD',
    name: 'Bulk Gymnema Sylvestre Capsules',
    slug: 'bulk-gymnema',
    brand_name: 'Bulk',
    brand_website: 'https://www.bulk.com',
    tier: 'economic',
    rrp: 7.99, rrp_currency: 'GBP',
    certifications: [],
    packet_text: 'Gymnema Sylvestre Extract 400mg. 90 capsules.',
    link_generic_ingredient: 'gymnema sylvestre gurmar supplement',
    ingredient_id: 'ingredient:gymnema-sylvestre',
    dose_per_serving: '400', unit: 'mg', form: 'Gymnema extract',
  },

  // ─── SAMe ──────────────────────────────────────────────────────────────────
  {
    id: 'product:jarrow-same-400',
    asin: 'B00020IN18',
    name: 'Jarrow Formulas SAM-e 400',
    slug: 'jarrow-same-400',
    brand_name: 'Jarrow Formulas',
    brand_website: 'https://www.jarrow.com',
    tier: 'aspiration',
    rrp: 39.99, rrp_currency: 'GBP',
    certifications: ['GMP'],
    packet_text: 'SAM-e (S-Adenosyl-L-Methionine) 400mg. 60 enteric-coated tablets. Full potency guaranteed. Take 1 tablet daily on an empty stomach. Store in refrigerator after opening.',
    link_generic_ingredient: 'SAMe S-adenosylmethionine supplement',
    ingredient_id: 'ingredient:same',
    dose_per_serving: '400', unit: 'mg', form: 'Enteric-coated tablet',
  },
  {
    id: 'product:nowfoods-same-200',
    asin: 'B001GA0G0S',
    name: 'NOW Foods SAM-e 200mg',
    slug: 'nowfoods-same-200',
    brand_name: 'NOW Foods',
    brand_website: 'https://www.nowfoods.com',
    tier: 'rational',
    rrp: 24.99, rrp_currency: 'GBP',
    certifications: ['GMP', 'Non-GMO'],
    packet_text: 'SAM-e (S-Adenosyl-L-Methionine) 200mg. 60 tablets. Enteric-coated. Take 1-2 tablets daily between meals.',
    link_generic_ingredient: 'SAMe S-adenosylmethionine supplement',
    ingredient_id: 'ingredient:same',
    dose_per_serving: '200', unit: 'mg', form: 'Enteric-coated tablet',
  },
  {
    id: 'product:naturesplus-same',
    asin: 'B000GGW8U8',
    name: 'Nature\'s Plus SAM-e',
    slug: 'naturesplus-same',
    brand_name: 'NaturesPlus',
    brand_website: 'https://www.naturesplus.com',
    tier: 'economic',
    rrp: 18.99, rrp_currency: 'GBP',
    certifications: ['GMP'],
    packet_text: 'SAM-e 200mg. 30 tablets. Take 1-2 tablets daily between meals.',
    link_generic_ingredient: 'SAMe S-adenosylmethionine supplement',
    ingredient_id: 'ingredient:same',
    dose_per_serving: '200', unit: 'mg', form: 'SAMe tablet',
  },

  // ─── MARINE COLLAGEN ───────────────────────────────────────────────────────
  {
    id: 'product:absolute-collagen-marine',
    asin: 'B07WKPP1XL',
    name: 'Absolute Collagen Marine Collagen Sachets',
    slug: 'absolute-collagen-marine',
    brand_name: 'Absolute Collagen',
    brand_website: 'https://www.absolutecollagen.com',
    tier: 'aspiration',
    rrp: 49.99, rrp_currency: 'GBP',
    certifications: ['GMP'],
    packet_text: 'Hydrolysed Marine Collagen 8,000mg per sachet. 28 sachets. Type I and III collagen from fish skin. Take 1 sachet daily.',
    link_official: 'https://www.absolutecollagen.com',
    link_generic_ingredient: 'hydrolysed marine collagen fish collagen supplement',
    ingredient_id: 'ingredient:marine-collagen',
    dose_per_serving: '8000', unit: 'mg', form: 'Hydrolysed marine collagen liquid',
  },
  {
    id: 'product:vital-proteins-marine-collagen',
    asin: 'B076KPWF5N',
    name: 'Vital Proteins Marine Collagen',
    slug: 'vital-proteins-marine-collagen',
    brand_name: 'Vital Proteins',
    brand_website: 'https://www.vitalproteins.com',
    tier: 'rational',
    rrp: 29.99, rrp_currency: 'GBP',
    certifications: ['GMP', 'Non-GMO'],
    packet_text: 'Hydrolysed Marine Collagen 12g per serving. 221g powder. Wild-caught fish. Unflavoured. Mix 2 scoops in water, coffee, or smoothie.',
    link_generic_ingredient: 'hydrolysed marine collagen fish collagen supplement',
    ingredient_id: 'ingredient:marine-collagen',
    dose_per_serving: '12000', unit: 'mg', form: 'Hydrolysed marine collagen powder',
  },
  {
    id: 'product:bulk-marine-collagen',
    asin: 'B07Y3MJHFV',
    name: 'Bulk Marine Collagen Powder',
    slug: 'bulk-marine-collagen',
    brand_name: 'Bulk',
    brand_website: 'https://www.bulk.com',
    tier: 'economic',
    rrp: 12.99, rrp_currency: 'GBP',
    certifications: [],
    packet_text: 'Hydrolysed Marine Collagen 10g per serving. 300g powder. From fish skin. Unflavoured.',
    link_generic_ingredient: 'hydrolysed marine collagen fish collagen supplement',
    ingredient_id: 'ingredient:marine-collagen',
    dose_per_serving: '10000', unit: 'mg', form: 'Hydrolysed marine collagen powder',
  },

  // ─── SELENIUM ──────────────────────────────────────────────────────────────
  {
    id: 'product:thorne-selenium',
    asin: 'B00451EHY4',
    name: 'Thorne Selenomethionine',
    slug: 'thorne-selenium',
    brand_name: 'Thorne',
    brand_website: 'https://www.thorne.com',
    tier: 'aspiration',
    rrp: 14.99, rrp_currency: 'GBP',
    certifications: ['NSF Certified for Sport', 'GMP'],
    packet_text: 'Selenium (as selenomethionine) 200mcg. 60 capsules. Organic form for superior bioavailability.',
    link_generic_ingredient: 'selenium selenomethionine supplement',
    ingredient_id: 'ingredient:selenium',
    dose_per_serving: '200', unit: 'mcg', form: 'Selenomethionine',
  },
  {
    id: 'product:solgar-selenium',
    asin: 'B00020II3A',
    name: 'Solgar Selenium',
    slug: 'solgar-selenium',
    brand_name: 'Solgar',
    brand_website: 'https://www.solgar.com',
    tier: 'rational',
    rrp: 8.99, rrp_currency: 'GBP',
    certifications: ['Kosher', 'GMP'],
    packet_text: 'Selenium (as l-selenomethionine) 100mcg. 100 tablets. Take 1 tablet daily.',
    link_generic_ingredient: 'selenium selenomethionine supplement',
    ingredient_id: 'ingredient:selenium',
    dose_per_serving: '100', unit: 'mcg', form: 'L-selenomethionine',
  },
  {
    id: 'product:nowfoods-selenium',
    asin: 'B001GA0F28',
    name: 'NOW Foods Selenium',
    slug: 'nowfoods-selenium',
    brand_name: 'NOW Foods',
    brand_website: 'https://www.nowfoods.com',
    tier: 'economic',
    rrp: 6.99, rrp_currency: 'GBP',
    certifications: ['GMP', 'Non-GMO'],
    packet_text: 'Selenium (from yeast) 200mcg. 180 veg capsules. Take 1 capsule daily with food.',
    link_generic_ingredient: 'selenium supplement',
    ingredient_id: 'ingredient:selenium',
    dose_per_serving: '200', unit: 'mcg', form: 'Selenium yeast',
  },

  // ─── IRON ──────────────────────────────────────────────────────────────────
  {
    id: 'product:solgar-gentle-iron',
    asin: 'B000GG5UBW',
    name: 'Solgar Gentle Iron 20mg',
    slug: 'solgar-gentle-iron',
    brand_name: 'Solgar',
    brand_website: 'https://www.solgar.com',
    tier: 'aspiration',
    rrp: 9.99, rrp_currency: 'GBP',
    certifications: ['Kosher', 'GMP'],
    packet_text: 'Iron (as iron bisglycinate) 20mg. 90 vegetable capsules. Gentle on the stomach. Take 1 capsule daily between meals.',
    link_generic_ingredient: 'iron bisglycinate gentle iron supplement',
    ingredient_id: 'ingredient:iron',
    dose_per_serving: '20', unit: 'mg', form: 'Iron bisglycinate',
  },
  {
    id: 'product:spatone-iron-sachets',
    asin: 'B01LXFVS5U',
    name: 'Spatone Natural Iron Supplement',
    slug: 'spatone-iron-sachets',
    brand_name: 'Spatone',
    brand_website: 'https://www.spatone.com',
    tier: 'rational',
    rrp: 14.99, rrp_currency: 'GBP',
    certifications: ['GMP'],
    packet_text: 'Natural iron water sachets. Each 30ml sachet provides 5mg iron. 28 sachets. Take 1-2 sachets daily. High bioavailability from natural Welsh spring.',
    link_generic_ingredient: 'iron supplement liquid sachets',
    ingredient_id: 'ingredient:iron',
    dose_per_serving: '5', unit: 'mg', form: 'Natural iron water',
  },
  {
    id: 'product:bulk-iron-bisglycinate',
    asin: 'B07CXWXTHB',
    name: 'Bulk Iron Bisglycinate Capsules',
    slug: 'bulk-iron-bisglycinate',
    brand_name: 'Bulk',
    brand_website: 'https://www.bulk.com',
    tier: 'economic',
    rrp: 5.99, rrp_currency: 'GBP',
    certifications: [],
    packet_text: 'Iron (as iron bisglycinate) 14mg per capsule. 120 capsules. Take 1-2 capsules daily.',
    link_generic_ingredient: 'iron bisglycinate gentle iron supplement',
    ingredient_id: 'ingredient:iron',
    dose_per_serving: '14', unit: 'mg', form: 'Iron bisglycinate',
  },
];

async function connectDb(): Promise<Surreal> {
  const url = process.env.SURREALDB_URL ?? 'http://localhost:8000';
  const ns = process.env.SURREALDB_NS ?? 'supplifyed';
  const database = process.env.SURREALDB_DB ?? 'production';
  const username = process.env.SURREALDB_USER ?? 'root';
  const password = process.env.SURREALDB_PASS ?? 'root';
  const db = new Surreal();
  await db.connect(url);
  await db.signin({ username, password });
  await db.use({ namespace: ns, database });
  return db;
}

async function upsertBrand(db: Surreal, name: string, website: string): Promise<RecordId> {
  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  const rid = new RecordId('brand', slug);
  await db.upsert(rid).content({
    name,
    website,
    affiliate_network: 'amazon',
    affiliate_link: website,
  });
  return rid;
}

async function seedProductsExpanded() {
  console.log('Connecting to SurrealDB...');
  const db = await connectDb();

  const tag = process.env.AMAZON_PARTNER_TAG ?? 'supplifyed-21';

  console.log(`Seeding ${PRODUCTS.length} expanded products...\n`);

  let productsOk = 0;
  let edgesOk = 0;
  let errors = 0;

  const brandCache = new Map<string, RecordId>();

  for (const seed of PRODUCTS) {
    const [pTable, ...pIdParts] = seed.id.split(':');
    const productRid = new RecordId(pTable, pIdParts.join(':'));
    const [ingTable, ...ingIdParts] = seed.ingredient_id.split(':');
    const ingredientRid = new RecordId(ingTable, ingIdParts.join(':'));

    try {
      if (!brandCache.has(seed.brand_name)) {
        const brandRid = await upsertBrand(db, seed.brand_name, seed.brand_website);
        brandCache.set(seed.brand_name, brandRid);
      }
      const brandRid = brandCache.get(seed.brand_name)!;

      await db.upsert(productRid).content({
        asin: seed.asin,
        name: seed.name,
        slug: seed.slug,
        brand_id: brandRid.toString(),
        tier: seed.tier,
        rrp: seed.rrp,
        rrp_currency: seed.rrp_currency,
        certifications: seed.certifications,
        packet_text: seed.packet_text,
        ...(seed.link_official ? { link_official: seed.link_official } : {}),
        link_amazon: `https://www.amazon.co.uk/dp/${seed.asin}?tag=${tag}`,
        link_generic: `https://www.amazon.co.uk/s?k=${encodeURIComponent(seed.link_generic_ingredient)}&tag=${tag}`,
        link_status: 'live' as const,
        source: 'bestseller_scrape',
        last_verified: new Date(),
      });

      await db.query(
        `RELATE $productId->made_by->$brandId`,
        { productId: productRid, brandId: brandRid }
      );

      await db.query(
        `RELATE $productId->contains->$ingredientId SET dose_per_serving = $dose, unit = $unit, form = $form`,
        {
          productId: productRid,
          ingredientId: ingredientRid,
          dose: seed.dose_per_serving,
          unit: seed.unit,
          form: seed.form,
        }
      );

      console.log(`  ✓ [${seed.tier.padEnd(10)}] ${seed.name}`);
      productsOk++;
      edgesOk++;
    } catch (err) {
      console.error(`  ✗ ${seed.id}: ${err}`);
      errors++;
    }
  }

  await db.close();
  console.log(`\n${productsOk} products · ${edgesOk} CONTAINS edges · ${errors} errors`);
  if (errors > 0) process.exit(1);
}

seedProductsExpanded().catch((err) => {
  console.error('Fatal:', err);
  process.exit(1);
});
