/**
 * Seeds the 90 remaining ingredients (Phase 2 + Phase 3) to complete 100 total.
 * Run: npm run seed:ingredients:scale
 * Requires Phase 1 ingredients already seeded: npm run seed:ingredients
 */

import { Surreal, RecordId } from 'surrealdb';

type IngredientSeed = {
  name: string;
  slug: string;
  category: string;
  description: string;
  primary_use: string[];
  evidence_rating: 'strong' | 'moderate' | 'mixed' | 'limited';
  dose_context: string;
  legal_notes?: string;
};

const INGREDIENTS: IngredientSeed[] = [

  // ─── PROTEIN & AMINO ACIDS ────────────────────────────────────────────────

  {
    name: 'Whey Protein Concentrate',
    slug: 'whey-protein-concentrate',
    category: 'Protein',
    description: 'Whey protein concentrate (WPC) is the least-processed whey form, typically yielding 70–80% protein by weight. It retains more fat and lactose than isolate but is substantially cheaper per gram. The most widely sold protein supplement globally.',
    primary_use: ['muscle protein synthesis', 'muscle mass', 'recovery', 'protein supplementation'],
    evidence_rating: 'strong',
    dose_context: 'Studies show 20–40g leucine-rich protein per serving maximises muscle protein synthesis (MPS). WPC delivers sufficient leucine at standard serving sizes. Marginally slower absorption than WPI due to fat and lactose content, but clinical outcome differences vs WPI are small when total daily protein is matched.',
  },
  {
    name: 'Casein Protein',
    slug: 'casein-protein',
    category: 'Protein',
    description: 'Micellar casein is a slow-digesting milk protein that forms a gel in the stomach, releasing amino acids over 5–7 hours. Evidence supports its use for overnight muscle protein synthesis and reducing overnight muscle breakdown in resistance-trained individuals.',
    primary_use: ['overnight muscle protein synthesis', 'anti-catabolism', 'recovery', 'sleep nutrition'],
    evidence_rating: 'strong',
    dose_context: '30–40g before sleep is the protocol used in studies showing benefits for overnight recovery. The slow digestion profile (vs fast whey) produces a sustained but lower MPS peak, which is advantageous for overnight periods without additional protein intake.',
  },
  {
    name: 'Pea Protein',
    slug: 'pea-protein',
    category: 'Protein',
    description: 'Pea protein isolate is extracted from yellow split peas and provides a complete amino acid profile. The fastest-growing vegan protein category. Evidence shows comparable gains to whey in some studies, with slightly lower leucine content per gram.',
    primary_use: ['muscle protein synthesis', 'vegan protein source', 'muscle mass', 'recovery'],
    evidence_rating: 'moderate',
    dose_context: 'Comparative studies have used 25g pea protein vs 25g whey post-exercise. Pea protein has approximately 8% leucine vs 10–11% in WPI, so a slightly larger dose (30g vs 25g) achieves equivalent leucine delivery. Digestibility is slightly lower than whey but higher than most plant proteins.',
  },
  {
    name: 'Egg Protein',
    slug: 'egg-protein',
    category: 'Protein',
    description: 'Egg white protein (ovalbumin) has a biological value of 100, the reference standard for protein quality. It is completely lactose-free, making it suitable for dairy-intolerant individuals. Evidence for muscle protein synthesis is strong; evidence specific to egg protein powder supplements is smaller than for whey.',
    primary_use: ['muscle protein synthesis', 'lactose-free protein source', 'muscle mass', 'recovery'],
    evidence_rating: 'strong',
    dose_context: '20–40g per serving to meet the leucine threshold. Egg white protein has approximately 9% leucine content, slightly below WPI. Historically used as the reference protein in amino acid research; evidence base for protein quality is strong, though supplement-specific trials are fewer than for whey.',
  },
  {
    name: 'Soy Protein Isolate',
    slug: 'soy-protein-isolate',
    category: 'Protein',
    description: 'Soy protein isolate is a complete plant protein with all essential amino acids. The most studied plant protein for muscle building. Contains phytoestrogens (isoflavones), which at typical dietary doses do not meaningfully affect testosterone or oestrogen in healthy adults based on evidence.',
    primary_use: ['muscle protein synthesis', 'vegan protein source', 'cardiovascular health', 'muscle mass'],
    evidence_rating: 'strong',
    dose_context: '25–30g per serving in comparative studies. Meta-analyses show soy protein supports muscle mass gains with resistance training, though response is typically slightly lower than whey per gram due to lower leucine content (approximately 8%). The phytoestrogen concern at supplement doses is not supported by current evidence in healthy adults.',
  },
  {
    name: 'Rice Protein',
    slug: 'rice-protein',
    category: 'Protein',
    description: 'Rice protein is extracted from brown rice and is often combined with pea protein to improve the amino acid profile. Low in lysine as a standalone protein. One comparative study found similar gains to whey over 8 weeks when dose was matched.',
    primary_use: ['vegan protein source', 'muscle protein synthesis', 'hypoallergenic protein'],
    evidence_rating: 'moderate',
    dose_context: 'Studies have used 48g/day rice protein vs whey in matched-dose comparisons. Low standalone lysine content (essential for collagen synthesis and protein metabolism) means rice protein is less complete than whey or soy. Most commercial rice protein products are combined with pea protein to correct this limitation.',
  },
  {
    name: 'Hemp Protein',
    slug: 'hemp-protein',
    category: 'Protein',
    description: 'Hemp protein is derived from hemp seeds and contains all essential amino acids, though protein content per gram is low (typically 30–50% protein by weight vs 80–90% for isolates). Rich in omega-3 fatty acids alongside its protein content. Evidence specifically for hemp protein supplementation is limited.',
    primary_use: ['vegan protein source', 'omega-3 content', 'fibre content'],
    evidence_rating: 'limited',
    dose_context: 'No large-scale RCTs specifically on hemp protein powder supplementation. Protein content is typically 30–50g per 100g, meaning a 30g serving delivers only 9–15g protein — below the leucine threshold for maximising MPS. Hemp protein is generally unsuitable as a primary protein supplement for muscle building at typical serving sizes.',
  },
  {
    name: 'BCAA Blend',
    slug: 'bcaa-blend',
    category: 'Amino Acids',
    description: 'Branched-chain amino acid blends contain leucine, isoleucine, and valine in a 2:1:1 ratio. Evidence for BCAAs as a standalone supplement has weakened as protein research matured — if dietary protein intake is adequate (≥1.6g/kg/day), additional BCAA supplementation provides minimal additional muscle building benefit.',
    primary_use: ['intra-workout amino delivery', 'leucine supplementation', 'protein timing'],
    evidence_rating: 'moderate',
    dose_context: 'Studies showing BCAA benefits used 5–20g/day. Effect is primarily driven by leucine content. Meta-analyses show BCAAs provide marginal benefit over adequate total protein intake, but may reduce muscle soreness (DOMS) in some populations. Most relevant for individuals with low dietary protein or in calorie restriction.',
  },
  {
    name: 'Leucine',
    slug: 'leucine',
    category: 'Amino Acids',
    description: 'Leucine is the primary branched-chain amino acid responsible for activating the mTOR (mechanistic target of rapamycin) pathway — the main signalling cascade for muscle protein synthesis. It is the key trigger for MPS regardless of source and is the reason high-leucine proteins (whey, egg) are superior for MPS per gram.',
    primary_use: ['mTOR activation', 'muscle protein synthesis trigger', 'anti-catabolism'],
    evidence_rating: 'strong',
    dose_context: 'Approximately 2–3g leucine per meal is required to maximally stimulate MPS in young adults; older adults may require 3–4g. Leucine threshold concept explains why protein source matters. Standalone leucine supplementation is most useful when total protein intake is adequate but individual meals are leucine-insufficient.',
  },
  {
    name: 'Isoleucine',
    slug: 'isoleucine',
    category: 'Amino Acids',
    description: 'Isoleucine is the second branched-chain amino acid after leucine. Evidence for standalone isoleucine supplementation is limited. It plays roles in glucose uptake into muscle cells and haemoglobin synthesis. Most relevant as part of a complete BCAA or EAA supplement rather than in isolation.',
    primary_use: ['glucose metabolism', 'muscle energy', 'part of BCAA blend'],
    evidence_rating: 'moderate',
    dose_context: 'Typically consumed as part of BCAA blends (1 part isoleucine : 2 parts leucine : 1 part valine in standard 2:1:1 ratios). Standalone isoleucine RCTs in humans are limited. Dose in blend context: 1.25–5g as part of a 5–20g BCAA supplement.',
  },
  {
    name: 'Valine',
    slug: 'valine',
    category: 'Amino Acids',
    description: 'Valine is the third branched-chain amino acid. Evidence for standalone valine supplementation is minimal — it is primarily consumed as part of BCAA blends. Plays a role in glucose-alanine cycle and energy metabolism during exercise. The weakest evidence base of the three BCAAs when studied alone.',
    primary_use: ['energy metabolism', 'part of BCAA blend', 'nitrogen balance'],
    evidence_rating: 'moderate',
    dose_context: 'Used as part of BCAA blends. Standard ratio provides 1 part valine to 2 parts leucine. Standalone valine RCTs in humans essentially absent. No established single-use dose recommendation for valine supplementation apart from BCAA context.',
  },
  {
    name: 'Essential Amino Acids',
    slug: 'essential-amino-acids',
    category: 'Amino Acids',
    description: 'Essential amino acid (EAA) blends contain all nine essential amino acids that the body cannot synthesise: leucine, isoleucine, valine, lysine, methionine, phenylalanine, threonine, tryptophan, and histidine. EAAs stimulate MPS more effectively than BCAAs alone because non-essential AAs are also needed for protein synthesis.',
    primary_use: ['muscle protein synthesis', 'complete amino profile', 'anti-catabolism', 'performance nutrition'],
    evidence_rating: 'strong',
    dose_context: '6–15g EAA per dose in studies showing MPS benefits, with leucine content driving the primary effect. EAA supplementation is particularly effective for older adults (who have reduced anabolic sensitivity) and populations with inadequate dietary protein. EAAs are superior to BCAAs alone when total protein intake is limited.',
  },
  {
    name: 'L-Glutamine',
    slug: 'l-glutamine',
    category: 'Amino Acids',
    description: 'Glutamine is the most abundant free amino acid in the bloodstream and muscle tissue. Evidence for gut health applications (intestinal permeability, IBS) is more consistent than for muscle building. Muscle building claims are not well-supported when dietary protein intake is adequate, as glutamine is conditionally essential — synthesised in sufficient amounts by healthy individuals.',
    primary_use: ['gut health', 'intestinal permeability', 'immune support', 'recovery'],
    evidence_rating: 'mixed',
    dose_context: 'Clinical gut health studies used 5–45g/day. For muscle recovery, 0.1g/kg bodyweight post-exercise is commonly used, with inconsistent results. Most muscle-specific benefits disappear when total protein is controlled. Gut health evidence is more consistent, particularly in clinical populations with intestinal conditions.',
  },
  {
    name: 'L-Arginine',
    slug: 'l-arginine',
    category: 'Amino Acids',
    description: 'L-Arginine is a precursor to nitric oxide (NO), theoretically improving blood flow and exercise performance. However, oral arginine has poor bioavailability — much is broken down in the gut and liver before reaching circulation. L-Citrulline (which converts to arginine in the kidney) is more effective at raising plasma arginine than arginine itself.',
    primary_use: ['nitric oxide precursor', 'blood flow', 'pump effect'],
    evidence_rating: 'mixed',
    dose_context: 'Oral arginine has 70% first-pass degradation in the gut. Studies using arginine to raise NO have mixed results, with many showing no significant effect at typical supplement doses (3–6g). L-Citrulline at 6–8g raises plasma arginine more effectively than 6g of arginine itself. For NO and pump effects, citrulline is the evidence-preferred choice.',
  },
  {
    name: 'L-Citrulline',
    slug: 'l-citrulline',
    category: 'Amino Acids',
    description: 'L-Citrulline is an amino acid that converts to arginine in the kidneys, raising plasma arginine and nitric oxide more effectively than arginine supplementation. Evidence shows improvements in exercise performance, blood pressure reduction, and reduction in post-exercise muscle soreness at appropriate doses.',
    primary_use: ['nitric oxide production', 'exercise performance', 'blood pressure', 'pump effect', 'DOMS reduction'],
    evidence_rating: 'strong',
    dose_context: '6–8g L-citrulline (or 8–10g citrulline malate) taken 60 minutes before exercise in performance studies. Meta-analyses confirm significant improvements in repetitions to failure and reduction in post-exercise soreness. Higher dose range (8g) associated with greater NO elevation and performance benefit than lower doses.',
  },
  {
    name: 'Citrulline Malate',
    slug: 'citrulline-malate',
    category: 'Amino Acids',
    description: 'Citrulline malate is L-citrulline bound to malic acid in a 2:1 ratio. Malic acid participates in the Krebs cycle, potentially adding aerobic energy production benefits to citrulline\'s NO-mediated effects. The most common form used in pre-workout supplements. Evidence base is strong for exercise performance.',
    primary_use: ['exercise performance', 'nitric oxide', 'aerobic and anaerobic output', 'DOMS reduction'],
    evidence_rating: 'strong',
    dose_context: '8g citrulline malate (providing approximately 5.3g L-citrulline) taken 60 minutes before exercise is the dose used in performance studies. Some RCTs show citrulline malate outperforms pure citrulline for aerobic capacity, potentially due to malate\'s Krebs cycle contribution, though evidence on this is not definitive.',
  },
  {
    name: 'Beta-Alanine',
    slug: 'beta-alanine',
    category: 'Amino Acids',
    description: 'Beta-alanine is a precursor to carnosine, a muscle buffer that reduces acidosis during high-intensity exercise. Evidence is consistent for improved performance in activities lasting 60–240 seconds. Associated with paraesthesia (harmless skin tingling) at typical doses, which is a well-documented and benign side effect.',
    primary_use: ['exercise endurance', 'high-intensity performance', 'carnosine synthesis', 'muscle buffering'],
    evidence_rating: 'strong',
    dose_context: '3.2–6.4g/day is the evidence-based dose range. Effects are cumulative — carnosine levels build over 4–12 weeks of supplementation, meaning single-dose acute use provides less benefit than consistent daily use. Paraesthesia (tingling) can be reduced by splitting into 800mg–1.6g doses throughout the day. Sustained-release formulations reduce tingling.',
  },
  {
    name: 'Taurine',
    slug: 'taurine',
    category: 'Amino Acids',
    description: 'Taurine is a conditionally essential amino acid involved in cardiovascular function, bile acid conjugation, antioxidant activity, and skeletal muscle function. Present in high concentrations in energy drinks (the only beverage category with it). Evidence covers cardiovascular benefits, exercise performance, and possible neuroprotective effects.',
    primary_use: ['cardiovascular function', 'exercise performance', 'antioxidant', 'heart function'],
    evidence_rating: 'moderate',
    dose_context: '500mg–3g per day in cardiovascular and exercise studies. Meta-analyses show modest improvements in aerobic exercise capacity and cardiovascular markers. Common energy drink dose (1g) is within the evidence range. Taurine is non-stimulant — its presence in energy drinks does not itself cause stimulant effects.',
  },
  {
    name: 'Glycine',
    slug: 'glycine',
    category: 'Amino Acids',
    description: 'Glycine is the smallest amino acid and serves multiple roles: collagen synthesis cofactor, neurotransmitter (inhibitory), glutathione precursor, and sleep quality modulator. Evidence for sleep quality improvement and collagen synthesis support is more consistent than other proposed benefits.',
    primary_use: ['sleep quality', 'collagen synthesis', 'glycine deficiency', 'neurotransmitter support'],
    evidence_rating: 'moderate',
    dose_context: '3g before sleep is the dose used in sleep quality RCTs showing reduced sleep onset latency and improved sleep quality. For collagen synthesis, glycine is consumed alongside collagen peptides (which are glycine-rich) or via gelatin. Typical dietary glycine intake is approximately 2–3g/day; the body synthesises approximately 3g/day.',
  },
  {
    name: 'L-Tyrosine',
    slug: 'l-tyrosine',
    category: 'Amino Acids',
    description: 'L-Tyrosine is a precursor to catecholamine neurotransmitters (dopamine, norepinephrine, epinephrine) and thyroid hormones. Evidence shows it reduces cognitive decline under acute stressors (sleep deprivation, cold, multi-tasking) but has limited effect in non-stressed individuals. Most relevant for cognitive resilience under demand.',
    primary_use: ['cognitive performance under stress', 'neurotransmitter precursor', 'thyroid support', 'working memory'],
    evidence_rating: 'moderate',
    dose_context: '100–300mg/kg bodyweight in acute cognitive stress studies, typically 500–2000mg. Effective primarily when endogenous catecholamine systems are depleted by stress, cold, or sleep deprivation. Minimal benefit in well-rested unstressed individuals. N-Acetyl-L-Tyrosine (NALT) has greater bioavailability but most research uses plain L-tyrosine.',
  },
  {
    name: 'L-Carnitine',
    slug: 'l-carnitine',
    category: 'Amino Acids',
    description: 'L-Carnitine is involved in fatty acid transport into mitochondria for beta-oxidation. Fat loss claims from supplementation are not well-supported in healthy individuals with adequate dietary intake. Evidence is stronger for populations with carnitine deficiency (vegans, elderly, kidney disease patients) and for fertility outcomes in men.',
    primary_use: ['fatty acid metabolism', 'male fertility', 'carnitine deficiency', 'cognitive support in elderly'],
    evidence_rating: 'mixed',
    dose_context: '1–3g/day in clinical studies. Fat loss benefit has not been consistently shown in healthy well-nourished adults. Meta-analyses show moderate benefit for male fertility markers (sperm motility and concentration) at 2g/day. Vegans have significantly lower carnitine stores and may show greater response to supplementation than omnivores.',
  },
  {
    name: 'Acetyl-L-Carnitine',
    slug: 'acetyl-l-carnitine',
    category: 'Amino Acids',
    description: 'Acetyl-L-Carnitine (ALCAR) is a form of carnitine that crosses the blood-brain barrier more effectively than L-carnitine. Evidence for cognitive and neuroprotective effects is more consistent than for fat loss. Used in studies on mild cognitive impairment, neuropathy, and age-related cognitive decline.',
    primary_use: ['cognitive support', 'neuroprotection', 'mitochondrial function', 'neuropathy'],
    evidence_rating: 'moderate',
    dose_context: '1.5–3g/day in cognitive and neuroprotective studies. More relevant than L-carnitine for cognitive applications due to CNS penetration. Peripheral neuropathy studies show significant symptom reduction. Cognitive benefits are clearest in impaired populations (MCI, elderly, diabetic neuropathy) rather than healthy young adults.',
  },
  {
    name: 'HMB',
    slug: 'hmb',
    category: 'Amino Acids',
    description: 'HMB (beta-hydroxy beta-methylbutyrate) is a leucine metabolite with proposed anti-catabolic effects. Evidence is inconsistent — benefits appear most reliable in untrained individuals beginning resistance training and in clinical populations (elderly, cachectic patients) rather than experienced athletes with adequate protein intake.',
    primary_use: ['anti-catabolism', 'muscle preservation', 'recovery in elderly', 'body composition'],
    evidence_rating: 'mixed',
    dose_context: '3g/day (1g three times daily) in most studies. Meta-analyses show statistically significant but modest benefits for lean mass and strength in untrained individuals; effects diminish or disappear in well-trained athletes with adequate protein. Most cost-effective when protein intake is already adequate and training experience is moderate.',
  },

  // ─── PERFORMANCE AND MINERALS ─────────────────────────────────────────────

  {
    name: 'Creatine HCL',
    slug: 'creatine-hcl',
    category: 'Performance',
    description: 'Creatine hydrochloride is creatine bound to hydrochloric acid, increasing solubility in water. Marketed at lower doses than monohydrate due to claimed superior absorption. Direct head-to-head comparison studies vs monohydrate at matched creatine doses are limited. Evidence base substantially smaller than monohydrate.',
    primary_use: ['muscle strength', 'power output', 'solubility preference'],
    evidence_rating: 'moderate',
    dose_context: 'Manufacturers typically recommend 750mg–1.5g HCL vs 3–5g monohydrate, claiming equivalent efficacy at lower doses. Independent comparative studies are limited. Solubility advantage is real, but whether this translates to superior muscle phosphocreatine loading vs monohydrate is unproven. No head-to-head trial has shown HCL superiority over monohydrate at equivalent creatine content.',
  },
  {
    name: 'Creatine Nitrate',
    slug: 'creatine-nitrate',
    category: 'Performance',
    description: 'Creatine nitrate combines creatine with nitrate, theoretically providing both creatine and NO precursor benefits. Has the least independent evidence of all creatine forms. The nitrate component may offer minor vasodilation benefits, but the combined product has minimal independent RCT evidence.',
    primary_use: ['muscle strength', 'nitric oxide', 'solubility'],
    evidence_rating: 'limited',
    dose_context: 'Studies are limited and most are manufacturer-funded. Proposed dose: 1–3g creatine nitrate. No large independent trials comparing creatine nitrate to monohydrate at matched creatine doses. Premium pricing vs monohydrate is not justified by the current evidence base.',
  },
  {
    name: 'Betaine Anhydrous',
    slug: 'betaine-anhydrous',
    category: 'Performance',
    description: 'Betaine (trimethylglycine) is found naturally in beets, spinach, and wheat germ. Evidence for exercise performance is emerging — studies show improvements in power output and body composition in some trials. Plays a role in homocysteine metabolism and methyl group donation.',
    primary_use: ['exercise performance', 'power output', 'homocysteine metabolism', 'body composition'],
    evidence_rating: 'moderate',
    dose_context: '2.5g/day in most performance studies. Meta-analysis data shows modest but significant improvements in muscle endurance and power. Effect size is smaller than creatine monohydrate. Most well-studied in lower-body exercises. Does not require loading; effects may take 2–4 weeks to accumulate.',
  },
  {
    name: 'Electrolyte Blend',
    slug: 'electrolyte-blend',
    category: 'Performance',
    description: 'Electrolyte blends typically combine sodium, potassium, magnesium, and chloride to replace minerals lost through sweat during exercise. Evidence is strong for preventing exercise-associated hyponatraemia in endurance athletes and for rehydration efficiency over plain water. Commercial electrolyte drinks (LMNT, Precision Hydration) are categorically distinct from basic sports drinks.',
    primary_use: ['hydration', 'exercise performance', 'electrolyte replenishment', 'endurance sports'],
    evidence_rating: 'strong',
    dose_context: 'Sweat sodium losses range 460–1840mg per litre of sweat (wide individual variation). Post-exercise rehydration requires replacing both fluid and electrolytes — plain water without sodium can worsen hyponatraemia in extreme cases. Standard electrolyte blends: 300–1000mg sodium, 200–400mg potassium per litre of fluid. Composition varies widely between products.',
  },
  {
    name: 'Sodium',
    slug: 'sodium',
    category: 'Minerals',
    description: 'Sodium is the primary extracellular electrolyte, essential for fluid balance, nerve conduction, and muscle contraction. Most people in developed countries consume excess sodium from food. Supplemental sodium is relevant primarily for endurance athletes with high sweat losses, those on sodium-restricted diets, and clinical sodium deficiency.',
    primary_use: ['electrolyte balance', 'fluid retention', 'nerve function', 'endurance performance'],
    evidence_rating: 'strong',
    dose_context: 'General population: sodium intake should not exceed 2300mg/day (NHS/WHO). Athletes with sweat losses >1.5L/hour may need 500–1000mg sodium per hour of exercise. Hyponatraemia (low sodium) in endurance athletes is caused by excessive plain water intake without sodium replacement — sodium supplementation is genuinely important in this context.',
  },
  {
    name: 'Potassium',
    slug: 'potassium',
    category: 'Minerals',
    description: 'Potassium is the primary intracellular electrolyte, critical for cellular fluid balance, nerve signalling, and muscle contraction including cardiac muscle. Most supplemental potassium products are capped at 99mg per serving by EU/UK regulations due to hyperkalemia risk at higher supplemental doses.',
    primary_use: ['electrolyte balance', 'cardiovascular health', 'blood pressure', 'muscle function'],
    evidence_rating: 'strong',
    dose_context: 'UK reference nutrient intake: 3500mg/day (predominantly from food — bananas, potatoes, leafy greens). The 99mg regulatory cap on supplements means supplemental contribution is minimal. Evidence is strong for potassium from dietary sources for blood pressure reduction. Supplemental potassium at regulatory cap doses has limited standalone clinical evidence.',
    legal_notes: 'UK/EU regulatory cap: maximum 99mg potassium per serving due to hyperkalemia risk at higher supplemental doses. Check local regulations before purchasing high-dose potassium products.',
  },
  {
    name: 'Zinc',
    slug: 'zinc',
    category: 'Minerals',
    description: 'Zinc is an essential mineral involved in over 300 enzymatic reactions, immune function, protein synthesis, DNA repair, and testosterone metabolism. Zinc deficiency significantly impairs immune function and wound healing. Form matters: bisglycinate and picolinate have higher bioavailability than oxide.',
    primary_use: ['immune function', 'testosterone support', 'wound healing', 'DNA synthesis', 'protein synthesis'],
    evidence_rating: 'strong',
    dose_context: 'RDA: 9.5mg (men), 7mg (women). Upper tolerable limit: 25mg/day (EU/UK). Zinc supplementation studies for immune function use 10–30mg/day. Picolinate has approximately 30% better bioavailability than gluconate. Oxide has poor bioavailability. At-risk groups: vegetarians, the elderly, and those with gastrointestinal conditions absorb zinc less efficiently.',
  },
  {
    name: 'Calcium',
    slug: 'calcium',
    category: 'Minerals',
    description: 'Calcium is the most abundant mineral in the human body, primarily stored in bone and teeth. Evidence is strong for bone density, particularly in combination with vitamin D3. The D3+K2+calcium combination represents the evidence-backed approach to bone mineral density support. Calcium supplementation without vitamin D has weaker evidence.',
    primary_use: ['bone density', 'muscle contraction', 'nerve function', 'cardiovascular function'],
    evidence_rating: 'strong',
    dose_context: 'UK RDA: 700mg/day. Most adults consume 500–800mg dietary calcium. Supplemental calcium in studies: 500–1200mg/day, most effective alongside vitamin D3 (800–2000 IU). High-dose calcium supplementation (>1500mg/day from all sources) has been associated with increased cardiovascular risk in some studies — this is at doses above the tolerable upper intake level.',
  },
  {
    name: 'Phosphorus',
    slug: 'phosphorus',
    category: 'Minerals',
    description: 'Phosphorus is the second most abundant mineral in the body, essential for ATP production, bone mineralisation, DNA/RNA synthesis, and acid-base balance. Most people in developed countries get more than adequate phosphorus from diet — it is found in virtually all protein foods. Deficiency is rare in healthy adults.',
    primary_use: ['ATP energy production', 'bone health', 'DNA synthesis', 'acid-base balance'],
    evidence_rating: 'moderate',
    dose_context: 'UK RDA: 550mg/day. Average dietary intake in developed countries is 1200–1600mg/day — significantly above the RDA. Deficiency is clinically rare in healthy adults. Supplemental phosphorus has limited applications beyond clinical phosphate depletion scenarios.',
  },
  {
    name: 'Chromium Picolinate',
    slug: 'chromium-picolinate',
    category: 'Minerals',
    description: 'Chromium is a trace mineral claimed to enhance insulin sensitivity and support blood sugar control. Picolinate is the most bioavailable supplemental form. Evidence for blood sugar effects is mixed — some studies show modest improvements in insulin sensitivity in diabetic or insulin-resistant populations, with limited evidence in healthy individuals.',
    primary_use: ['insulin sensitivity', 'blood glucose control', 'carbohydrate metabolism'],
    evidence_rating: 'mixed',
    dose_context: '200–1000mcg chromium picolinate/day in studies. Meta-analyses show statistically significant but clinically modest improvements in fasting blood glucose and HbA1c in type 2 diabetics. Evidence in non-diabetic populations is weak. The EFSA has not approved health claims for chromium picolinate for blood glucose regulation at this time.',
  },
  {
    name: 'Boron',
    slug: 'boron',
    category: 'Minerals',
    description: 'Boron is a trace mineral with proposed roles in bone health, testosterone metabolism, and vitamin D metabolism. Testosterone claims have minimal independent evidence — most studies are small, short-duration, or manufacturer-funded. Evidence for bone health (calcium and magnesium retention) is more consistent but modest.',
    primary_use: ['bone health', 'testosterone metabolism', 'vitamin D metabolism'],
    evidence_rating: 'limited',
    dose_context: '3–10mg/day in bone and hormone studies. No established UK/EU RDA. Evidence for testosterone effects: one study found 10mg boron for 1 week increased free testosterone by approximately 28%, but this small study has not been widely replicated. Bone health data indicates boron helps maintain calcium and magnesium but effect size is modest.',
  },

  // ─── VITAMINS ─────────────────────────────────────────────────────────────

  {
    name: 'Vitamin K2 (MK-7)',
    slug: 'vitamin-k2-mk7',
    category: 'Vitamins',
    description: 'Vitamin K2 MK-7 is the menaquinone form of vitamin K, which activates proteins that direct calcium to bone (osteocalcin) and away from arteries (matrix GLA protein). The D3+K2 combination is increasingly studied for bone health — vitamin D increases calcium absorption while K2 ensures it is deposited in bone rather than soft tissue.',
    primary_use: ['bone mineralisation', 'arterial calcium management', 'vitamin D cofactor', 'cardiovascular health'],
    evidence_rating: 'moderate',
    dose_context: 'MK-7 at 90–200mcg/day in bone density studies. MK-7 has a much longer half-life than MK-4, allowing once-daily dosing. Evidence for combined D3+K2 on bone density is emerging but not yet at the strength of D3+calcium alone. Potential arterial calcification prevention benefit is biologically plausible but not fully established in RCTs.',
  },
  {
    name: 'Vitamin C',
    slug: 'vitamin-c',
    category: 'Vitamins',
    description: 'Vitamin C (ascorbic acid) is a water-soluble antioxidant essential for collagen synthesis, immune function, iron absorption, and neurotransmitter synthesis. Evidence is strong for its role in deficiency prevention (scurvy) and immune support. Liposomal formulations claim superior absorption over standard ascorbic acid — the absorption difference is real at doses above 500mg.',
    primary_use: ['immune function', 'collagen synthesis', 'antioxidant', 'iron absorption', 'skin health'],
    evidence_rating: 'strong',
    dose_context: 'UK RDA: 40mg/day. Upper tolerable limit: 1000mg/day. Plasma saturation occurs at approximately 200mg/day — above this, absorption decreases and urinary excretion increases. Common supplement doses of 500–1000mg exceed what can be absorbed from a single dose of standard ascorbic acid. Liposomal forms maintain absorption efficiency at higher single doses. Vitamin C at 200mg/day is the dose where immune benefits plateau in non-deficient individuals.',
  },
  {
    name: 'Vitamin A',
    slug: 'vitamin-a',
    category: 'Vitamins',
    description: 'Vitamin A includes retinoids (preformed vitamin A from animal sources) and carotenoids (provitamins from plants). Essential for vision, immune function, and cellular differentiation. Preformed vitamin A (retinol/retinyl palmitate) is hepatotoxic in excess — the only fat-soluble vitamin with a well-documented acute toxicity ceiling at doses reached by excessive supplementation.',
    primary_use: ['vision', 'immune function', 'skin health', 'cellular differentiation'],
    evidence_rating: 'strong',
    dose_context: 'UK RDA: 700mcg RAE (men), 600mcg RAE (women). Tolerable upper intake level: 3000mcg RAE/day. Supplemental preformed vitamin A above 1500mcg/day long-term has been associated with reduced bone density. Beta-carotene (plant-based provitamin A) does not have the same toxicity ceiling — conversion to retinol is regulated. Most people in developed countries are not deficient.',
  },
  {
    name: 'Vitamin E',
    slug: 'vitamin-e',
    category: 'Vitamins',
    description: 'Vitamin E refers to a family of eight compounds (four tocopherols, four tocotrienols). Alpha-tocopherol is the most bioactive form but supplementing with only alpha-tocopherol may deplete gamma-tocopherol, which has distinct anti-inflammatory properties. Evidence for vitamin E supplementation benefits in non-deficient healthy adults is weak. Natural vs synthetic form matters: d-alpha-tocopherol vs dl-alpha-tocopherol.',
    primary_use: ['antioxidant', 'immune function', 'skin health', 'vitamin E deficiency'],
    evidence_rating: 'mixed',
    dose_context: 'UK RDA: 4mg (men), 3mg (women) — easily met from diet (nuts, seeds, vegetable oils). Upper tolerable limit: 540mg/day. Supplementation in non-deficient healthy adults has not consistently shown clinical benefits in large RCTs. Some meta-analyses indicate high-dose supplementation (≥400 IU/day) may increase all-cause mortality — this remains debated.',
  },
  {
    name: 'Vitamin B1 (Thiamine)',
    slug: 'vitamin-b1-thiamine',
    category: 'Vitamins',
    description: 'Thiamine is a water-soluble B vitamin essential for carbohydrate metabolism and neural function. Deficiency causes beriberi and Wernicke-Korsakoff syndrome. Deficiency is rare in developed countries from diet alone but common in heavy alcohol users. Supplementation is relevant for deficiency correction, not general performance enhancement in replete individuals.',
    primary_use: ['carbohydrate metabolism', 'neural function', 'thiamine deficiency correction', 'energy production'],
    evidence_rating: 'strong',
    dose_context: 'UK RDA: 1mg (men), 0.8mg (women). Deficiency correction doses: 10–100mg/day. At-risk groups: heavy alcohol users, bariatric surgery patients, elderly with poor nutrition. In replete healthy adults, additional thiamine supplementation beyond RDA does not improve performance or health outcomes with current evidence.',
  },
  {
    name: 'Vitamin B2 (Riboflavin)',
    slug: 'vitamin-b2-riboflavin',
    category: 'Vitamins',
    description: 'Riboflavin is essential for energy production (FAD and FMN coenzymes), antioxidant function, and homocysteine metabolism. Strong evidence exists for migraine prevention at high doses. In clinical populations, riboflavin 400mg/day has been shown to reduce migraine frequency significantly.',
    primary_use: ['energy production', 'migraine prevention', 'homocysteine metabolism', 'antioxidant'],
    evidence_rating: 'strong',
    dose_context: 'UK RDA: 1.3mg (men), 1.1mg (women). For migraine prevention: 400mg/day — significantly above RDA. Large systematic reviews confirm riboflavin 400mg/day as a safe, evidence-based migraine prophylaxis option with a well-tolerated side effect profile (orange-yellow urine discolouration is harmless). For general supplementation in non-deficient adults, dose is RDA level.',
  },
  {
    name: 'Vitamin B3 (Niacin)',
    slug: 'vitamin-b3-niacin',
    category: 'Vitamins',
    description: 'Niacin (vitamin B3) exists as nicotinic acid and niacinamide (nicotinamide). At high doses, nicotinic acid (not niacinamide) is a potent lipid-modifying agent, raising HDL cholesterol and lowering triglycerides. Causes characteristic skin flushing at pharmacological doses. Niacinamide does not cause flushing but also lacks the lipid effects.',
    primary_use: ['lipid modification', 'HDL cholesterol increase', 'energy metabolism', 'NAD+ precursor'],
    evidence_rating: 'strong',
    dose_context: 'UK RDA: 16.5mg NE (men), 13.2mg NE (women). Pharmacological lipid modification: 1000–3000mg/day nicotinic acid — far above RDA, requires medical supervision. Flush-free niacin products (inositol hexanicotinate) have poor absorption and do not produce lipid effects. For NAD+ precursor effects at RDA doses, niacinamide is the preferred form.',
  },
  {
    name: 'Vitamin B5 (Pantothenic Acid)',
    slug: 'vitamin-b5',
    category: 'Vitamins',
    description: 'Pantothenic acid is a component of coenzyme A (CoA), essential for fatty acid synthesis and metabolism. Claims that pantothenic acid helps acne are not well-supported by evidence. Deficiency is practically unknown in developed countries due to ubiquitous food distribution. Supplementation in non-deficient adults has no established benefit.',
    primary_use: ['CoA synthesis', 'fatty acid metabolism', 'energy production', 'adrenal support'],
    evidence_rating: 'moderate',
    dose_context: 'UK adequate intake: 200mg/day — easily met from diet. Acne studies using high-dose pantothenic acid (2.2g/day) showed mixed results — the evidence does not currently support this use. No established upper tolerable limit as toxicity has not been reported. Supplementation serves primarily to prevent deficiency, which is rare in populations with adequate food access.',
  },
  {
    name: 'Vitamin B6 (Pyridoxine)',
    slug: 'vitamin-b6',
    category: 'Vitamins',
    description: 'Vitamin B6 (pyridoxine/P5P/pyridoxal) is involved in over 100 enzymatic reactions, particularly amino acid metabolism, neurotransmitter synthesis, and homocysteine metabolism. P5P (pyridoxal-5-phosphate) is the active form. Note: chronic high-dose supplementation (>50mg/day) is associated with peripheral neuropathy. The MHRA reduced the UK safe upper limit to 10mg/day in 2024.',
    primary_use: ['amino acid metabolism', 'neurotransmitter synthesis', 'homocysteine control', 'PMS symptom support'],
    evidence_rating: 'strong',
    dose_context: 'UK RDA: 1.4mg (men), 1.2mg (women). Evidence-based upper limit: 10mg/day long-term (MHRA 2024 guidance). Peripheral neuropathy risk increases above 10–50mg/day with long-term use. P5P (pyridoxal-5-phosphate) is the metabolically active form — direct supplementation of P5P may be preferable to pyridoxine HCL for those with conversion issues. PMS evidence uses 50–100mg — now above updated safe limits.',
    legal_notes: 'MHRA (UK) reduced the safe daily upper limit for vitamin B6 to 10mg/day in 2023 due to peripheral neuropathy risk at higher chronic doses. Products above 10mg/day may be subject to regulatory review.',
  },
  {
    name: 'Vitamin B7 (Biotin)',
    slug: 'vitamin-b7-biotin',
    category: 'Vitamins',
    description: 'Biotin is a water-soluble B vitamin involved in fatty acid synthesis, gluconeogenesis, and amino acid metabolism. Marketed heavily for hair, skin, and nail improvements, but evidence supporting these claims in non-deficient individuals is weak. Biotin deficiency (which does cause hair loss) is rare. High-dose biotin interferes with thyroid and troponin immunoassays, creating false laboratory results.',
    primary_use: ['fatty acid synthesis', 'gluconeogenesis', 'hair and nail health (in deficiency)', 'biotin deficiency'],
    evidence_rating: 'mixed',
    dose_context: 'UK adequate intake: 30–100mcg/day. Common supplement doses: 1000–10000mcg — massively above adequate intake. No evidence that supraphysiological biotin dosing benefits hair/nails in non-deficient individuals. Clinically important: biotin supplementation above 5000mcg can interfere with immunoassay-based blood tests (thyroid function, troponin), causing falsely low or high results.',
  },
  {
    name: 'Vitamin B9 (Folate)',
    slug: 'vitamin-b9-folate',
    category: 'Vitamins',
    description: 'Folate (vitamin B9) is essential for DNA synthesis, repair, and methylation. The methylfolate form (5-MTHF) bypasses the MTHFR enzyme conversion step, making it preferable for the approximately 40% of people who carry MTHFR variants that impair folic acid conversion. Evidence is strong for neural tube defect prevention in pregnancy. Folic acid (synthetic form) and methylfolate differ in metabolism.',
    primary_use: ['DNA synthesis', 'neural tube defect prevention', 'homocysteine metabolism', 'methyl group donation', 'MTHFR variant support'],
    evidence_rating: 'strong',
    dose_context: 'UK RDA: 200mcg/day. Pregnancy: 400mcg/day for first 12 weeks (NHS guidance). 5-MTHF is the active form and preferred for individuals with MTHFR polymorphisms. Evidence for folic acid reducing neural tube defects is among the strongest in nutritional supplementation. Masking vitamin B12 deficiency is a concern with high-dose folic acid in the elderly.',
  },
  {
    name: 'Vitamin B12 (Methylcobalamin)',
    slug: 'vitamin-b12',
    category: 'Vitamins',
    description: 'Vitamin B12 is essential for nerve function, DNA synthesis, and red blood cell formation. Methylcobalamin and adenosylcobalamin are the active forms; cyanocobalamin (the most common supplement form) must be converted. Vegans and strict vegetarians are at significant risk of deficiency due to absence in plant foods. Absorption requires intrinsic factor — older adults commonly develop impaired absorption.',
    primary_use: ['nerve function', 'red blood cell formation', 'DNA synthesis', 'homocysteine metabolism', 'energy metabolism'],
    evidence_rating: 'strong',
    dose_context: 'UK RDA: 1.5mcg/day. Vegans require supplementation — NHS recommends daily B12 supplement or B12-fortified foods. High-dose oral B12 (1000–2000mcg) can correct deficiency even in those with impaired intrinsic factor via passive absorption. Methylcobalamin is preferred over cyanocobalamin for those who cannot efficiently convert cyanocobalamin. Deficiency symptoms: fatigue, neurological damage, megaloblastic anaemia.',
  },
  {
    name: 'Multivitamin Blend',
    slug: 'multivitamin',
    category: 'Vitamins',
    description: 'Multivitamin supplements contain a combination of vitamins and often minerals. Evidence from large RCTs (Physicians Health Study II, COSMOS) shows modest benefits for cancer risk reduction and cognitive outcomes but limited effect on cardiovascular disease prevention in well-nourished populations. Effect is greatest in nutritionally inadequate diets.',
    primary_use: ['nutrient insurance', 'deficiency prevention', 'micronutrient adequacy'],
    evidence_rating: 'mixed',
    dose_context: 'Effects vary substantially by baseline nutritional status. The COSMOS-MIND trial found daily multivitamin use improved memory and reduced cognitive decline in older adults over 3 years. Benefits are strongest for those with poor baseline micronutrient status. High-dose single vitamins (e.g. vitamin E >400 IU, vitamin A >2500 IU) have been associated with adverse outcomes — look for products at RDA-level dosing rather than megadose formulations.',
  },

  // ─── OMEGA OILS ──────────────────────────────────────────────────────────

  {
    name: 'Omega-3 EPA',
    slug: 'omega-3-epa',
    category: 'Omega Oils',
    description: 'Eicosapentaenoic acid (EPA) is a long-chain omega-3 fatty acid primarily associated with anti-inflammatory, cardiovascular, and mood effects. Pharmaceutical-grade EPA (icosapentaenoic acid at 4g/day, as in Vascepa) has shown significant cardiovascular event reduction. EPA is preferentially associated with mood regulation in depression research.',
    primary_use: ['cardiovascular protection', 'anti-inflammatory', 'mood support', 'triglyceride reduction'],
    evidence_rating: 'strong',
    dose_context: 'Cardiovascular meta-analyses: 1–4g EPA/day. The REDUCE-IT trial used 4g pure EPA/day as prescription Vascepa (manufacturer-funded). Anti-inflammatory effects: 2–4g combined EPA+DHA/day. For mood, pure EPA at 1–2g/day shows the strongest antidepressant augmentation evidence — DHA alone is less effective for mood outcomes.',
  },
  {
    name: 'Omega-3 DHA',
    slug: 'omega-3-dha',
    category: 'Omega Oils',
    description: 'Docosahexaenoic acid (DHA) is the primary structural omega-3 in the brain and retina, comprising approximately 40% of brain polyunsaturated fatty acids. Critical for infant neurodevelopment. In adults, evidence focuses on cognitive support, eye health, and reducing triglycerides. DHA is found in highest concentrations in brain grey matter and photoreceptors.',
    primary_use: ['brain structure', 'cognitive function', 'eye health', 'infant neurodevelopment', 'triglyceride reduction'],
    evidence_rating: 'strong',
    dose_context: 'Pregnancy DHA: 200mg/day minimum per European Food Safety Authority guidance. Cognitive support in adults: evidence is stronger for populations with low baseline DHA (vegans, elderly). Standard supplement: 250–500mg DHA/day. Algae oil provides DHA without fish, making it the vegan equivalent and the original biological source (fish accumulate DHA by eating algae).',
  },
  {
    name: 'Krill Oil',
    slug: 'krill-oil',
    category: 'Omega Oils',
    description: 'Krill oil provides EPA and DHA bound to phospholipids rather than triglycerides, which some evidence indicates improves absorption and brain uptake. Also contains astaxanthin (a carotenoid antioxidant). Claims of superior efficacy at lower doses vs fish oil remain contested — some pharmacokinetic studies show modest absorption advantage, but clinical outcome superiority is unproven.',
    primary_use: ['EPA and DHA delivery', 'phospholipid omega-3', 'astaxanthin source', 'cardiovascular health'],
    evidence_rating: 'moderate',
    dose_context: 'Studies use 1–3g krill oil/day. Phospholipid form does show approximately 10–15% better incorporation into red blood cell membranes than fish oil triglycerides in some studies, but head-to-head clinical outcome trials (not just biomarker studies) are limited. Higher cost per gram of EPA+DHA vs fish oil concentrates. Sustainability certification varies.',
  },
  {
    name: 'Algae Oil',
    slug: 'algae-oil',
    category: 'Omega Oils',
    description: 'Algae oil is derived from marine algae, the original source of EPA and DHA in the food chain. Fish accumulate omega-3s by eating algae. Algae oil provides a vegan source of long-chain omega-3s. DHA from algae oil shows comparable bioavailability and bioactivity to DHA from fish oil in direct comparison studies.',
    primary_use: ['vegan omega-3 source', 'DHA supplementation', 'EPA and DHA combined', 'sustainable sourcing'],
    evidence_rating: 'moderate',
    dose_context: 'Studies show algae DHA increases plasma and red blood cell DHA concentrations equivalently to fish oil DHA at matched doses. Standard algae oil products: 250–500mg DHA per capsule. Some algae oil products now provide EPA as well as DHA — the EPA fraction is smaller than in fish oil but growing. Suitable for vegans and those who cannot tolerate fish oil.',
  },
  {
    name: 'MCT Oil',
    slug: 'mct-oil',
    category: 'Omega Oils',
    description: 'Medium-chain triglycerides (MCTs) — caprylic (C8) and capric (C10) acids — are metabolised differently from long-chain fats, going directly to the liver where they can be rapidly converted to ketones. Popular in ketogenic diets. Evidence for weight loss is modest; evidence for acute cognitive effects from ketone production is present but effect sizes are small.',
    primary_use: ['ketone production', 'ketogenic diet support', 'rapid energy source', 'cognitive function'],
    evidence_rating: 'moderate',
    dose_context: '15–30ml/day (1–2 tablespoons) in most studies. C8 (caprylic acid) is the most ketogenic MCT fraction and is preferred over blended MCT oil for ketone production. Rapid addition of MCT oil causes gastrointestinal distress (diarrhoea, cramping) — clinical practice is to start with 5ml/day and titrate up. Energy density: 8.3 kcal/g, same as other fats despite the different metabolism.',
  },
  {
    name: 'CLA',
    slug: 'cla',
    category: 'Omega Oils',
    description: 'Conjugated linoleic acid (CLA) is a naturally occurring fatty acid found in meat and dairy from ruminant animals. Supplemental CLA is typically produced from safflower oil and is a mixture of CLA isomers. Fat loss claims come largely from studies in mice — human evidence shows statistically significant but clinically minimal fat reduction (approximately 0.1kg/week in meta-analyses).',
    primary_use: ['body composition', 'fat loss', 'lean mass', 'metabolic function'],
    evidence_rating: 'limited',
    dose_context: '3.2g/day is the dose used in most human studies. Meta-analyses show statistically significant but very small effects on body fat (approximately 0.1kg/week) — unlikely to be clinically meaningful for most users. CLA supplementation at high doses may adversely affect insulin sensitivity and lipid profiles in some individuals. The gap between animal study results and human results is particularly pronounced for CLA.',
  },
  {
    name: 'Flaxseed Oil',
    slug: 'flaxseed-oil',
    category: 'Omega Oils',
    description: 'Flaxseed oil is the richest plant source of alpha-linolenic acid (ALA), an omega-3 precursor. ALA must be converted to EPA and DHA for most omega-3 benefits — this conversion rate in humans is inefficient (approximately 5–10% to EPA, <1% to DHA). Flaxseed oil is not equivalent to fish or algae oil as an EPA/DHA source.',
    primary_use: ['ALA omega-3 source', 'vegan omega-3 precursor', 'anti-inflammatory potential'],
    evidence_rating: 'moderate',
    dose_context: 'ALA conversion efficiency: approximately 5–10% to EPA, less than 1% to DHA in most adults. For EPA+DHA equivalence, 10ml flaxseed oil (~6.3g ALA) converts to approximately 300–630mg EPA and minimal DHA — similar to one standard fish oil capsule (300mg EPA+DHA) but much less efficient. Direct algae oil supplementation is substantially more effective for raising plasma EPA and DHA vs flaxseed oil.',
  },

  // ─── GUT HEALTH ──────────────────────────────────────────────────────────

  {
    name: 'Probiotics (Multi-Strain)',
    slug: 'probiotics',
    category: 'Gut Health',
    description: 'Probiotic supplements contain live microorganisms that confer health benefits when administered in adequate amounts. Multi-strain formulations combine several bacterial species. Evidence is strain-specific — the strains used in a product determine its effectiveness for specific conditions. Not all probiotic products are evidence-backed for all claimed uses.',
    primary_use: ['gut microbiome support', 'IBS symptom reduction', 'immune function', 'antibiotic recovery', 'gut barrier integrity'],
    evidence_rating: 'moderate',
    dose_context: 'CFU counts range widely across products (1 billion to 500 billion CFU). Higher CFU counts are not inherently better — the strain matters more than the count for specific outcomes. Probiotic effects are condition-specific: Lactobacillus rhamnosus GG for antibiotic-associated diarrhoea; L. plantarum for IBS; Bifidobacterium infantis for IBS. Third-party verification of viable CFU counts at expiry date (not manufacture date) is clinically important.',
  },
  {
    name: 'Lactobacillus',
    slug: 'lactobacillus',
    category: 'Gut Health',
    description: 'Lactobacillus is the most widely studied probiotic genus, with multiple species showing evidence across gut health, immune function, and women\'s health applications. L. acidophilus, L. rhamnosus GG, and L. plantarum 299v have the most robust evidence bases within the genus. Strain-specificity is critical — different Lactobacillus strains have different mechanisms and evidence.',
    primary_use: ['gut microbiome', 'IBS', 'vaginal health', 'antibiotic recovery', 'immune function'],
    evidence_rating: 'strong',
    dose_context: 'L. rhamnosus GG: 10 billion CFU/day for prevention of antibiotic-associated diarrhoea (Grade A Cochrane evidence). L. plantarum 299v: 10–20 billion CFU/day for IBS. Most Lactobacillus strains are effective at 1–10 billion CFU/day for general microbiome support. Species and strain designation on the label is essential for evidence-based selection.',
  },
  {
    name: 'Bifidobacterium',
    slug: 'bifidobacterium',
    category: 'Gut Health',
    description: 'Bifidobacterium is the dominant probiotic genus in the colon of adults and breastfed infants. B. longum and B. infantis have the strongest evidence for IBS symptom reduction; B. lactis Bb-12 is well-studied for general gut health. Bifidobacterium levels decline with age, making supplementation more relevant for older adults.',
    primary_use: ['IBS symptoms', 'gut barrier', 'constipation', 'immune modulation', 'infant gut health'],
    evidence_rating: 'strong',
    dose_context: 'B. infantis 35624 (Alflorex): 1 billion CFU/day shown to reduce IBS global symptoms (Whorwell 2006). B. longum BB536: 1–10 billion CFU/day for immune and GI outcomes. Effective CFU counts are lower for Bifidobacterium than for Lactobacillus species — 1–10 billion CFU/day is supported across most strains studied. Refrigeration required for most Bifidobacterium products.',
  },
  {
    name: 'Prebiotic Fibre',
    slug: 'prebiotic-fibre',
    category: 'Gut Health',
    description: 'Prebiotic fibres (primarily FOS, GOS, inulin, and resistant starch) are selectively fermented by beneficial gut bacteria, promoting their growth. Evidence is strong for stimulating Bifidobacterium growth, supporting gut barrier function, and improving bowel regularity. Prebiotics feed the probiotics — the combination (synbiotics) may be more effective than either alone.',
    primary_use: ['microbiome support', 'Bifidobacterium growth', 'bowel regularity', 'gut barrier'],
    evidence_rating: 'strong',
    dose_context: '5–15g/day of prebiotic fibre in studies showing microbiome changes. Gastrointestinal side effects (gas, bloating) occur if dose is increased too rapidly — titrate up over 2–4 weeks. GOS (galacto-oligosaccharides) tend to be better tolerated than inulin at equivalent doses. Effect on bowel regularity occurs at 10–15g/day.',
  },
  {
    name: 'Inulin',
    slug: 'inulin',
    category: 'Gut Health',
    description: 'Inulin is a specific prebiotic fibre (fructan) extracted predominantly from chicory root. Strong evidence for selectively promoting Bifidobacterium growth. Also reduces serum cholesterol modestly and improves bowel regularity. Long-chain inulin (HP inulin) shows stronger bifidogenic effects than short-chain FOS.',
    primary_use: ['Bifidobacterium promotion', 'bowel regularity', 'cholesterol reduction', 'satiety'],
    evidence_rating: 'strong',
    dose_context: '5–10g/day inulin shows consistent bifidogenic effects in studies. At 10–12g/day, modest LDL cholesterol reduction (approximately 0.3 mmol/L) has been documented. Bloating and flatulence are dose-dependent side effects — starting at 2–3g/day and increasing over weeks minimises discomfort. Naturally found in chicory, Jerusalem artichoke, garlic, and onions.',
  },
  {
    name: 'Psyllium Husk',
    slug: 'psyllium-husk',
    category: 'Gut Health',
    description: 'Psyllium husk is a soluble fibre derived from Plantago ovata seeds. Evidence is among the strongest of any dietary supplement for two distinct outcomes: LDL cholesterol reduction and bowel regularity (both constipation and diarrhoea-predominant IBS). FDA-approved health claim for cardiovascular benefits. The only fibre supplement with this level of evidence across both lipid and gut outcomes.',
    primary_use: ['LDL cholesterol reduction', 'bowel regularity', 'IBS', 'blood glucose management', 'satiety'],
    evidence_rating: 'strong',
    dose_context: '5–15g/day psyllium husk. For cholesterol: meta-analyses show 3.5–5g psyllium fibre three times daily reduces LDL by approximately 7–8% independently of diet. For IBS-C and IBS-D: 5g twice daily. Must be taken with ample water (≥200ml per gram of psyllium) to prevent oesophageal or intestinal obstruction. Can be taken as powder, capsules, or as Metamucil/Fybogel.',
  },
  {
    name: 'Digestive Enzymes',
    slug: 'digestive-enzymes',
    category: 'Gut Health',
    description: 'Digestive enzyme supplements contain amylase (carbohydrates), protease (proteins), lipase (fats), and often lactase (lactose) and alpha-galactosidase (gas-producing oligosaccharides). Evidence is clearest for specific enzyme deficiencies: lactase for lactose intolerance, pancrelipase for exocrine pancreatic insufficiency. Evidence for general use in healthy adults without diagnosed deficiency is limited.',
    primary_use: ['lactose digestion', 'bloating reduction', 'protein digestion', 'fat malabsorption'],
    evidence_rating: 'moderate',
    dose_context: 'Lactase supplements: 3000–9000 FCC units per dairy serving — well-evidenced for lactose intolerance. Alpha-galactosidase (Beano): reduces gas from beans and cruciferous vegetables — evidence-based. Broad-spectrum enzyme blends for "improved digestion" in healthy individuals: evidence is modest. Most benefit is seen in diagnosed enzyme insufficiency, not general wellness. Take immediately before meals.',
  },
  {
    name: 'Postbiotics',
    slug: 'postbiotics',
    category: 'Gut Health',
    description: 'Postbiotics are bioactive compounds produced when gut bacteria ferment prebiotic fibres — including short-chain fatty acids (SCFAs), peptides, cell wall fragments, and metabolites. Heat-killed (tyndallised) bacteria and bacterial extracts are also categorised as postbiotics. The category is newer than probiotics and prebiotics, with a growing but still emerging evidence base.',
    primary_use: ['gut barrier function', 'immune modulation', 'SCFA production', 'microbiome support'],
    evidence_rating: 'moderate',
    dose_context: 'Emerging category without established dosing norms. Heat-killed L. paracasei (Postbiotic HK-LP) at 1–10 billion cells/day shows immune and gut barrier effects in some trials. Butyrate (a SCFA postbiotic) at 300–600mg/day has evidence for gut barrier support. Evidence substantially less established than for probiotics. ISAPP (International Scientific Association for Prebiotics and Probiotics) formalised the postbiotic definition in 2021.',
  },

  // ─── HERBAL AND PLANT EXTRACTS ────────────────────────────────────────────

  {
    name: 'Turmeric / Curcumin',
    slug: 'turmeric-curcumin',
    category: 'Herbal',
    description: 'Curcumin is the primary bioactive polyphenol in turmeric root. It has potent in vitro anti-inflammatory activity, but oral bioavailability of standard curcumin is extremely poor. Formulation matters critically: piperine (black pepper extract, BioPerine) increases bioavailability 20-fold; liposomal, phytosome (Meriva), and nano-curcumin formulations further improve absorption. Unformulated curcumin powder has minimal clinical utility.',
    primary_use: ['anti-inflammatory', 'joint health', 'antioxidant', 'gut health', 'neuroprotection'],
    evidence_rating: 'moderate',
    dose_context: '500–2000mg curcumin with piperine or in bioavailable formulation. Standard turmeric powder contains approximately 3% curcumin — a teaspoon of turmeric (~2g) delivers only ~60mg curcumin, far below therapeutic doses. Meriva (phytosome form) at 500–1000mg twice daily or BCM-95 at 1000mg/day are the formulations with most clinical study. Always check the form, not just the dose.',
  },
  {
    name: 'Green Tea Extract',
    slug: 'green-tea-extract',
    category: 'Herbal',
    description: 'Green tea extract contains catechins (primarily EGCG), caffeine, and L-theanine. EGCG has antioxidant and modest metabolic effects. Evidence for fat oxidation, modest thermogenesis, and cognitive benefits is present but effect sizes are small. The combination of caffeine and L-theanine from green tea produces alert-but-calm cognitive effects.',
    primary_use: ['antioxidant', 'fat oxidation', 'cognitive alertness', 'metabolic support'],
    evidence_rating: 'moderate',
    dose_context: '300–800mg EGCG/day in metabolic studies. Green tea extract standardised to ≥45% EGCG is required for consistent dosing. Caffeine content varies (10–100mg per serving) and should be considered when stacking. High-dose GTE supplements (>800mg EGCG/day) have been associated with rare liver toxicity — stay within evidence-based doses. L-theanine+caffeine combination: 200mg L-theanine + 100mg caffeine for cognitive effects.',
  },
  {
    name: 'Rhodiola Rosea',
    slug: 'rhodiola-rosea',
    category: 'Herbal',
    description: 'Rhodiola rosea is an adaptogenic herb from northern Europe and Asia. Evidence supports reductions in stress-induced fatigue and mental performance decrements. Active constituents: salidroside and rosavins. Standardised extract (3% rosavins, 1% salidroside) is the form used in clinical trials.',
    primary_use: ['stress-induced fatigue reduction', 'cognitive performance under stress', 'adaptogen', 'mental endurance'],
    evidence_rating: 'moderate',
    dose_context: '200–600mg/day of standardised extract (SHR-5 and similar) in studies. Most effective for reducing stress-related cognitive fatigue rather than baseline performance enhancement in non-stressed individuals. Effect on burnout and occupational stress has been studied in clinical populations. Take in the morning due to mild stimulant-like properties that can affect sleep if taken late.',
  },
  {
    name: 'Ginseng',
    slug: 'ginseng',
    category: 'Herbal',
    description: 'Panax ginseng (Korean/Asian ginseng) is distinguished from Siberian ginseng (Eleutherococcus) and American ginseng (P. quinquefolius). Active compounds (ginsenosides) vary between species and preparation methods. Evidence covers cognitive function, fatigue reduction, immune support, and modest effects on erectile function. Standardised ginsenoside content is required for evidence-based dosing.',
    primary_use: ['cognitive function', 'fatigue reduction', 'immune support', 'adaptogen', 'sexual function'],
    evidence_rating: 'moderate',
    dose_context: '200–400mg Korean red ginseng extract (standardised to ≥4% ginsenosides) in most cognitive and fatigue studies. Korean red ginseng (steamed and dried) has more clinical evidence than raw white ginseng. Ginsenoside content varies 5–10-fold between products at equivalent doses — standardisation percentage is the key quality indicator. Effects on cognitive function appear after 4–8 weeks of consistent use.',
  },
  {
    name: 'Maca Root',
    slug: 'maca-root',
    category: 'Herbal',
    description: 'Maca (Lepidium meyenii) is a Peruvian root vegetable with a long traditional use for energy and libido. The evidence base is small — most studies are short-duration, small sample size, or use varying preparations. Some evidence for modest libido improvement (psychosexual function) and reduced sexual dysfunction in antidepressant users, but effect sizes are modest.',
    primary_use: ['libido support', 'energy', 'sexual function', 'hormonal balance'],
    evidence_rating: 'limited',
    dose_context: '1.5–3g dried maca powder or 500–1000mg extract in studies. Gelatinised maca has better digestibility than raw. Studies show no significant effect on testosterone or oestrogen levels despite libido effects — mechanism is not hormone-mediated. Multiple colours of maca exist (yellow, red, black) with claimed different effects; the evidence does not strongly differentiate between them.',
  },
  {
    name: 'Lion\'s Mane Mushroom',
    slug: 'lions-mane-mushroom',
    category: 'Herbal',
    description: 'Hericium erinaceus (Lion\'s Mane) contains hericenones and erinacines, which stimulate nerve growth factor (NGF) synthesis. Evidence is growing for cognitive benefits, particularly in older adults with mild cognitive impairment. The fruiting body contains hericenones; mycelium contains erinacines — both have activity. Fruiting body products are generally preferred in the supplement market.',
    primary_use: ['cognitive function', 'NGF stimulation', 'neuroprotection', 'mood support', 'nerve health'],
    evidence_rating: 'moderate',
    dose_context: '500–3000mg/day fruiting body or extract in cognitive studies. One RCT (Mori 2009, n=30 elderly with MCI) found 250mg dry powder three times daily (750mg/day) significantly improved cognitive scores vs placebo over 16 weeks. Fruiting body vs mycelium distinction matters — look for products specifying fruiting body and ≥30% beta-glucan content as a quality indicator.',
  },
  {
    name: 'Reishi Mushroom',
    slug: 'reishi-mushroom',
    category: 'Herbal',
    description: 'Ganoderma lucidum (Reishi) is a medicinal mushroom with traditional use in East Asia for immune function, sleep, and longevity. Active compounds include triterpenes (ganoderic acids) and polysaccharides (beta-glucans). Evidence supports immune modulation and modest sleep quality improvement. The sleep angle makes reishi distinct from most adaptogens.',
    primary_use: ['immune modulation', 'sleep quality', 'adaptogen', 'antioxidant', 'anti-inflammatory'],
    evidence_rating: 'moderate',
    dose_context: '1–3g dried reishi extract (containing ≥10% beta-glucans) in studies. Hot water extraction is required to release polysaccharides; alcohol extraction releases triterpenes — dual-extraction products target both compound classes. Anti-cancer claims are not supported by human clinical evidence at supplement doses. Most relevant as an immune and sleep support supplement.',
  },
  {
    name: 'Cordyceps',
    slug: 'cordyceps',
    category: 'Herbal',
    description: 'Cordyceps sinensis (now reclassified as Ophiocordyceps sinensis) is a parasitic fungus traditionally used in Tibetan medicine. CS-4 is the most-studied cultivated strain. Evidence for exercise performance (VO2 max, aerobic capacity) is present but inconsistent. Elite athlete studies show smaller effects than studies in sedentary older adults.',
    primary_use: ['aerobic performance', 'VO2 max', 'energy production', 'adaptogen', 'traditional medicine'],
    evidence_rating: 'moderate',
    dose_context: '1–3g CS-4 strain extract/day in performance studies. Effect on VO2 max: a meta-analysis found modest improvements averaging +0.7 ml/kg/min. Effects appear more pronounced in older or less-trained individuals. Natural Ophiocordyceps sinensis is extremely expensive; most products use CS-4 cultured mycelium. Check the strain designation — generic "cordyceps" products vary widely.',
  },
  {
    name: 'Milk Thistle',
    slug: 'milk-thistle',
    category: 'Herbal',
    description: 'Milk thistle (Silybum marianum) contains silymarin, a complex of flavonolignans (primarily silybin) with hepatoprotective properties. Evidence for liver protection in alcoholic liver disease, drug-induced liver injury, and cirrhosis is present, though effect sizes vary. Most relevant for liver stress contexts rather than general wellness in healthy livers.',
    primary_use: ['liver protection', 'hepatoprotection', 'antioxidant', 'cirrhosis support'],
    evidence_rating: 'moderate',
    dose_context: '420–600mg silymarin (70–80% silymarin extract) in 2–3 divided doses in hepatic studies. Silybin phytosome (Siliphos) has significantly better absorption than standard silymarin. Evidence in non-alcoholic fatty liver disease (NAFLD) shows modest improvements in liver enzymes. Evidence for cirrhosis reversal is weak. Most applicable for individuals with elevated liver enzymes or known hepatic stress.',
  },
  {
    name: 'Berberine',
    slug: 'berberine',
    category: 'Herbal',
    description: 'Berberine is a plant alkaloid found in barberry, goldenseal, and other plants. Evidence for blood glucose regulation (type 2 diabetes) is among the strongest of any herbal supplement — direct comparisons with metformin show comparable HbA1c and fasting glucose reduction, though berberine trials are generally smaller. Also lowers LDL cholesterol and triglycerides.',
    primary_use: ['blood glucose regulation', 'insulin sensitivity', 'LDL reduction', 'type 2 diabetes', 'AMPK activation'],
    evidence_rating: 'strong',
    dose_context: '500mg three times daily (1.5g/day total) is the standard dose from most clinical studies. One RCT directly compared berberine to metformin — comparable HbA1c reduction at 3 months. Takes 2–4 weeks for full effect. Bioavailability is limited due to P-glycoprotein efflux; dihydroberberine form has better absorption. Note: berberine interacts with multiple medications (particularly those metabolised by CYP450 enzymes) — consult a physician if on medications.',
  },
  {
    name: 'Fenugreek',
    slug: 'fenugreek',
    category: 'Herbal',
    description: 'Fenugreek seeds contain saponins (including furostanol saponins) proposed to support testosterone levels and insulin function. Evidence for testosterone effects is modest and mostly manufacturer-associated. Evidence for blood glucose and insulin effects is more consistent. Also has evidence for breastfeeding milk production, though evidence quality is variable.',
    primary_use: ['testosterone support', 'blood glucose', 'breast milk production', 'insulin sensitivity'],
    evidence_rating: 'moderate',
    dose_context: '500–1000mg standardised extract twice daily in testosterone studies; 500–600mg twice daily in glucose studies. Testosterone study results are inconsistent across independent research. The most reliable evidence involves blood glucose and postprandial insulin response — the fibre and saponin content may both contribute. Has a distinct maple-syrup taste/odour that appears in sweat and urine.',
  },
  {
    name: 'Tongkat Ali',
    slug: 'tongkat-ali',
    category: 'Herbal',
    description: 'Tongkat Ali (Eurycoma longifolia, Longjack) is a Southeast Asian plant with traditional use as an aphrodisiac and testosterone booster. LJ100 is the most studied standardised extract. Evidence shows modest increases in free testosterone and improved sexual health parameters, including in men with late-onset hypogonadism. Independent replication is limited.',
    primary_use: ['testosterone support', 'sexual function', 'libido', 'stress reduction', 'male health'],
    evidence_rating: 'moderate',
    dose_context: '200–400mg LJ100 standardised extract/day (1:200 water-extracted root, standardised to eurycomaoside content). A placebo-controlled RCT (n=76 men with late-onset hypogonadism) showed 200mg/day LJ100 for 1 month significantly normalised testosterone levels vs placebo. Most studies are small and some are manufacturer-associated. More evidence needed from independent large trials.',
  },
  {
    name: 'Tribulus Terrestris',
    slug: 'tribulus-terrestris',
    category: 'Herbal',
    description: 'Tribulus terrestris is marketed heavily as a testosterone booster and athletic performance enhancer. Current evidence does not support these claims — multiple RCTs in healthy men show no significant effect on testosterone, LH, or muscle mass. The testosterone-boosting claims originate from studies in infertile rats, which do not translate to healthy humans at typical supplement doses.',
    primary_use: ['libido support', 'sexual function', 'cardiovascular support'],
    evidence_rating: 'limited',
    dose_context: '750–1500mg/day of standardised extract in RCTs showing no testosterone or performance effect in healthy athletes. The evidence gap between marketing claims and independent human RCT data is significant for tribulus. A systematic review of 13 RCTs found no significant increase in testosterone, LH, or athletic performance. May have modest libido effects independent of testosterone.',
  },
  {
    name: 'Garlic Extract',
    slug: 'garlic-extract',
    category: 'Herbal',
    description: 'Garlic contains allicin (produced when raw garlic is crushed) and other organosulfur compounds. Evidence is consistent for modest blood pressure reduction (approximately 4–5 mmHg systolic), LDL reduction, and platelet aggregation inhibition. Aged garlic extract (AGE) provides allyl compounds without the odour of fresh garlic and has its own evidence base for cardiovascular benefits.',
    primary_use: ['blood pressure reduction', 'cardiovascular health', 'LDL reduction', 'antimicrobial', 'antioxidant'],
    evidence_rating: 'strong',
    dose_context: '600–1500mg/day aged garlic extract or equivalent allicin-releasing product in cardiovascular studies. A meta-analysis of 12 trials found garlic supplementation reduced systolic BP by approximately 4.6 mmHg and diastolic BP by 2.4 mmHg. Allicin stability varies between products — enteric-coated garlic powder standardised for allicin release or aged garlic extract (AGE) have the most reliable evidence.',
  },
  {
    name: 'Ginger Root',
    slug: 'ginger-root',
    category: 'Herbal',
    description: 'Ginger (Zingiber officinale) contains gingerols and shogaols with documented anti-emetic and anti-inflammatory properties. Evidence for reducing nausea and vomiting (post-operative, chemotherapy-induced, morning sickness) is among the strongest of any herbal supplement. Anti-inflammatory effects at supplement doses are present but modest.',
    primary_use: ['nausea and vomiting', 'morning sickness', 'anti-inflammatory', 'digestive support', 'joint health'],
    evidence_rating: 'strong',
    dose_context: '1000–2000mg dried ginger root or standardised extract in nausea studies. Cochrane review confirms ginger significantly reduces nausea and vomiting in pregnancy at 250mg four times daily. Post-operative nausea: 1g pre-operatively is effective. Anti-inflammatory (joint pain): 250–500mg standardised extract twice daily. Generally very safe; may increase bleeding risk at very high doses when combined with anticoagulants.',
  },
  {
    name: 'Cinnamon Extract',
    slug: 'cinnamon-extract',
    category: 'Herbal',
    description: 'Cinnamon contains cinnamaldehyde and other bioactives with proposed insulin-sensitising properties. Ceylon cinnamon (C. verum) is distinct from Cassia cinnamon (C. aromaticum) — Cassia contains significant coumarin (a blood thinner) which causes liver toxicity at high doses; Ceylon has negligible coumarin. Blood glucose claims are modest and evidence is mixed.',
    primary_use: ['blood glucose support', 'insulin sensitivity', 'antioxidant'],
    evidence_rating: 'moderate',
    dose_context: '1–6g/day cassia cinnamon or 1–3g/day Ceylon cinnamon in blood glucose studies. Meta-analyses show statistically significant but small reductions in fasting blood glucose (approximately 10 mg/dL) in type 2 diabetics. Evidence in non-diabetic individuals is weak. Cassia cinnamon above 1–2g/day should be avoided due to coumarin content — Ceylon cinnamon is the safe choice for regular supplementation.',
  },
  {
    name: 'Saw Palmetto',
    slug: 'saw-palmetto',
    category: 'Herbal',
    description: 'Saw palmetto (Serenoa repens) berry extract is widely used for benign prostatic hyperplasia (BPH) symptoms. It inhibits 5-alpha reductase (same mechanism as finasteride). Evidence is mixed — some meta-analyses show significant BPH symptom improvement, others (including a Cochrane review) show no benefit over placebo. Effects may be dose-dependent.',
    primary_use: ['BPH symptoms', '5-alpha reductase inhibition', 'prostate health', 'urinary flow'],
    evidence_rating: 'mixed',
    dose_context: '320mg/day of lipophilic saw palmetto extract (standardised to 85–95% fatty acids) is the most-studied dose. STEP trial (n=225, NEJM 2006) found no significant benefit vs placebo for BPH symptoms. CAMUS trial (n=369) found escalating doses up to 960mg/day no more effective than placebo. Smaller studies and meta-analyses show positive results — the evidence is genuinely mixed, not clearly positive or negative.',
  },

  // ─── RECOVERY, SLEEP AND LONGEVITY ───────────────────────────────────────

  {
    name: 'CoQ10',
    slug: 'coq10',
    category: 'Longevity',
    description: 'Coenzyme Q10 is a fat-soluble compound involved in mitochondrial electron transport and cellular energy production. CoQ10 levels decline with age and are depleted by statin medications. Evidence for statin-induced myopathy relief is mixed but supports a role in maintaining mitochondrial function in statin users. Ubiquinol (reduced form) has better bioavailability than ubiquinone (oxidised form).',
    primary_use: ['mitochondrial function', 'statin myopathy support', 'antioxidant', 'cardiovascular support', 'energy production'],
    evidence_rating: 'moderate',
    dose_context: '100–300mg/day ubiquinol or 200–600mg/day ubiquinone. Absorption is significantly improved when taken with a fatty meal. Ubiquinol is the active (reduced) form and crosses cellular membranes more efficiently — plasma CoQ10 levels are approximately 1.5–3× higher from ubiquinol vs equivalent ubiquinone doses. Evidence for clinical endpoints (cardiovascular events, HF outcomes) is mixed in well-nourished populations but stronger in deficiency states.',
  },
  {
    name: 'Ubiquinol',
    slug: 'ubiquinol',
    category: 'Longevity',
    description: 'Ubiquinol is the reduced, active form of coenzyme Q10. It is the dominant form of CoQ10 in blood (approximately 90% of circulating CoQ10). Older adults and those on statins may have impaired conversion of ubiquinone to ubiquinol, making the pre-reduced form more relevant for these populations. Bioavailability data consistently favours ubiquinol over ubiquinone.',
    primary_use: ['CoQ10 delivery', 'mitochondrial function', 'antioxidant protection', 'cardiovascular support'],
    evidence_rating: 'moderate',
    dose_context: '100–200mg/day ubiquinol, taken with fat. Multiple pharmacokinetic studies show 1.5–3× higher plasma CoQ10 from ubiquinol vs matched-dose ubiquinone. For statin users or those over 60 (when conversion efficiency decreases), ubiquinol is the preferred form. Same mitochondrial function and cardiovascular applications as CoQ10, with superior bioavailability as the distinguishing feature.',
  },
  {
    name: 'NMN',
    slug: 'nmn',
    category: 'Longevity',
    description: 'Nicotinamide mononucleotide (NMN) is a precursor to NAD+ (nicotinamide adenine dinucleotide), a coenzyme involved in hundreds of metabolic reactions and shown to decline with age in animal models. Early human trials show NMN supplementation increases NAD+ levels in blood. Whether raised NAD+ produces the longevity and health benefits observed in animal studies is not established in humans.',
    primary_use: ['NAD+ precursor', 'mitochondrial energy', 'longevity research', 'metabolic function'],
    evidence_rating: 'limited',
    dose_context: '250–500mg/day NMN in early human clinical trials. Phase 1 safety trial (Irie 2020, n=10): 100–500mg single dose safe and dose-dependently increased NAD+ in blood. Subsequent RCTs show NMN raises NAD+ but clinical benefit evidence (muscle function, metabolic markers) is inconsistent and effect sizes are small. The gap between mouse longevity data and human data remains unresolved. High commercial value despite limited human evidence.',
  },
  {
    name: 'Nicotinamide Riboside (NR)',
    slug: 'nicotinamide-riboside',
    category: 'Longevity',
    description: 'Nicotinamide riboside (NR) is an alternative NAD+ precursor to NMN. Both NR and NMN raise blood NAD+ levels, but whether peripheral blood NAD+ reflects tissue NAD+ (particularly in brain and muscle) is not established. NR has more published human clinical trials than NMN at this stage. Like NMN, it competes on the premise that raising NAD+ will translate animal longevity benefits to humans.',
    primary_use: ['NAD+ precursor', 'sirtuin activation', 'longevity research', 'energy metabolism'],
    evidence_rating: 'limited',
    dose_context: '250–1000mg/day NR (Niagen) in clinical trials. Multiple Phase 1 trials confirm NR safely raises NAD+ in blood. A 2018 trial (Martens et al., n=30) found 500mg NR twice daily increased NAD+ by 60% vs baseline. No large RCT has demonstrated clinical longevity or disease-prevention outcomes from NR in humans. NR is generally considered more evidence-backed than NMN due to more published human trials, though both have limited clinical outcome data.',
  },
  {
    name: 'Alpha Lipoic Acid',
    slug: 'alpha-lipoic-acid',
    category: 'Longevity',
    description: 'Alpha lipoic acid (ALA) is a potent antioxidant that functions in both aqueous and lipid environments and can regenerate other antioxidants (vitamins C and E, glutathione). Evidence is strongest for diabetic peripheral neuropathy, where 600mg/day has been shown to reduce symptoms. The R-ALA enantiomer is the naturally occurring active form; most supplements are racemic (R+S) mixtures.',
    primary_use: ['antioxidant', 'diabetic neuropathy', 'glucose metabolism', 'insulin sensitivity'],
    evidence_rating: 'moderate',
    dose_context: '600–1800mg/day in diabetic neuropathy studies; 600mg IV infusion is even more studied. Oral 600mg/day R-ALA reduces neuropathy symptoms in diabetic peripheral neuropathy (SYDNEY2 trial). For antioxidant and metabolic effects: 300–600mg/day of R-ALA or 600mg racemic ALA. R-ALA is more bioavailable than the S-enantiomer. Take on an empty stomach — food reduces absorption.',
  },
  {
    name: 'Resveratrol',
    slug: 'resveratrol',
    category: 'Longevity',
    description: 'Resveratrol is a polyphenol found in red wine, grapes, and Japanese knotweed. Animal studies (particularly in mice) showed remarkable longevity benefits via sirtuin activation. Human evidence has not replicated these findings — bioavailability is extremely poor (rapid metabolism means 70% is converted to metabolites before reaching systemic circulation), and clinical RCTs in healthy adults show minimal effects.',
    primary_use: ['sirtuin activation', 'antioxidant', 'cardiovascular research', 'longevity research'],
    evidence_rating: 'limited',
    dose_context: '100–500mg/day in human studies. Despite significant commercial interest, large-scale human RCTs have largely failed to demonstrate the cardiovascular and metabolic benefits seen in animal models. Bioavailability problem: resveratrol is rapidly sulphated and glucuronidated in the gut and liver. Micronised and liposomal forms improve but do not fully solve the bioavailability issue. The gap between animal data and human evidence is well-documented.',
  },
  {
    name: 'Hyaluronic Acid',
    slug: 'hyaluronic-acid',
    category: 'Recovery',
    description: 'Hyaluronic acid (HA) is a glycosaminoglycan naturally present in skin, joints, and connective tissue. Topical and injectable HA has strong evidence for skin hydration and joint lubrication. Oral HA supplements have emerging but debated evidence — bioavailability of orally consumed HA has been questioned, but studies do show elevated HA-related biomarkers after oral supplementation.',
    primary_use: ['joint lubrication', 'skin hydration', 'connective tissue support', 'eye health'],
    evidence_rating: 'moderate',
    dose_context: '80–200mg/day oral HA in joint and skin studies. A systematic review of 8 trials found oral HA (80–200mg/day) improved skin elasticity and reduced joint pain at 4–8 weeks. Molecular weight matters: low molecular weight HA (<50 kDa) is better absorbed orally than high molecular weight. Most clinical evidence uses 120–240mg low-to-medium molecular weight HA.',
  },
  {
    name: 'Glucosamine',
    slug: 'glucosamine',
    category: 'Recovery',
    description: 'Glucosamine sulphate is a structural component of joint cartilage, used to treat osteoarthritis (OA) symptoms. Evidence from older trials was encouraging; the large GAIT trial showed no benefit over placebo for most subgroups. European pharmaceutical-grade glucosamine sulphate (Dona, Rotta) consistently outperforms supplement-grade in trials, raising questions about whether grade matters for efficacy.',
    primary_use: ['joint pain', 'osteoarthritis', 'cartilage support', 'joint health'],
    evidence_rating: 'mixed',
    dose_context: '1500mg/day glucosamine sulphate (split doses) in most OA trials. GAIT trial (n=1583): glucosamine sulphate alone no better than placebo for mild OA; combination with chondroitin showed modest benefit for moderate-severe OA subgroup. European Pharmacy-grade (crystalline glucosamine sulphate, Dona) has more consistently positive results than supplement-grade products. Onset of effect takes 4–8 weeks of consistent use.',
  },
  {
    name: 'Chondroitin',
    slug: 'chondroitin',
    category: 'Recovery',
    description: 'Chondroitin sulphate is a glycosaminoglycan and structural component of cartilage. Usually sold in combination with glucosamine for joint health. Evidence is similar to glucosamine — mixed, with pharmaceutical-grade preparations showing more consistent benefits than supplement-grade. The GAIT trial found the glucosamine+chondroitin combination modestly helpful in moderate-severe OA.',
    primary_use: ['joint pain', 'osteoarthritis', 'cartilage support', 'joint health'],
    evidence_rating: 'mixed',
    dose_context: '800–1200mg/day chondroitin sulphate in OA studies. Often combined with glucosamine as GCS (glucosamine-chondroitin sulphate). EULAR guidelines give conditional recommendations for chondroitin in OA — positive effects are modest in well-designed trials. Pharmaceutical-grade products outperform supplement-grade. Time to effect: 4–8 weeks minimum; maximal benefit at 3–6 months.',
  },
  {
    name: 'MSM',
    slug: 'msm',
    category: 'Recovery',
    description: 'Methylsulfonylmethane (MSM) is an organosulfur compound that acts as a sulfur donor for connective tissue synthesis. Evidence for joint pain reduction in OA and exercise-induced muscle damage is present but modest. The sulfur content is proposed to support collagen and glutathione synthesis. Generally well-tolerated with few adverse effects.',
    primary_use: ['joint pain', 'anti-inflammatory', 'exercise recovery', 'cartilage support', 'antioxidant'],
    evidence_rating: 'moderate',
    dose_context: '1.5–6g/day MSM in joint and exercise recovery studies. A meta-analysis found significant improvements in pain and physical function in knee OA at 3g/day. For exercise-induced muscle damage: 3g/day for 2 weeks before a strenuous exercise test showed reduced oxidative damage markers. Generally combined with glucosamine and chondroitin in joint health products.',
  },
  {
    name: 'CBD Hemp Extract',
    slug: 'cbd-hemp-extract',
    category: 'Recovery',
    description: 'Cannabidiol (CBD) is a non-psychoactive cannabinoid from hemp (Cannabis sativa). Pharmaceutical CBD (Epidiolex) has FDA approval for specific epilepsy syndromes — the highest-quality evidence for CBD. For anxiety, the evidence is promising at 150–600mg/day in clinical populations. For sleep, pain, and general wellness, evidence in healthy adults is preliminary and effect sizes are small.',
    primary_use: ['anxiety reduction', 'sleep support', 'anti-inflammatory', 'pain management', 'neuroprotection'],
    evidence_rating: 'mixed',
    dose_context: 'Epilepsy (pharmaceutical Epidiolex): 10–20mg/kg/day. Anxiety studies: 150–600mg acute dose or 25–75mg/day chronic. Sleep: 25–175mg/day, with evidence for initial improvement but tolerance may develop. Most consumer CBD products contain 10–50mg per dose — well below doses used in clinical trials showing anxiolytic effects (300–600mg). Important note: legal status varies by country and jurisdiction.',
    legal_notes: 'Legal status varies by country. CBD products are legal in the UK when THC content is below 0.2%. In some EU countries CBD regulations differ. Pharmaceutical-grade CBD (Epidiolex) is prescription-only. Supplement-grade CBD products are food supplements in the UK. The FDA has not approved CBD as a food supplement in the USA. Check local regulations.',
  },
];

async function connectDb(): Promise<Surreal> {
  const url = process.env.SURREALDB_URL ?? 'http://localhost:8000';
  const ns  = process.env.SURREALDB_NS   ?? 'supplifyed';
  const database = process.env.SURREALDB_DB ?? 'production';
  const username = process.env.SURREALDB_USER ?? 'root';
  const password = process.env.SURREALDB_PASS ?? 'root';
  const db = new Surreal();
  await db.connect(url);
  await db.signin({ username, password });
  await db.use({ namespace: ns, database });
  return db;
}

async function seedIngredientsScale() {
  console.log('Connecting to SurrealDB...');
  const db = await connectDb();

  console.log(`Seeding ${INGREDIENTS.length} Phase 2/3 ingredients...\n`);

  let ok = 0;
  let errors = 0;

  for (const seed of INGREDIENTS) {
    try {
      await db.upsert(new RecordId('ingredient', seed.slug)).content({
        ...seed,
        last_verified: new Date(),
      });
      console.log(`  ✓ ${seed.name}`);
      ok++;
    } catch (err) {
      console.error(`  ✗ ${seed.name}: ${err}`);
      errors++;
    }
  }

  await db.close();

  console.log(`\n${ok} ingredients seeded · ${errors} errors`);
  if (errors > 0) process.exit(1);
}

seedIngredientsScale().catch((err) => {
  console.error('Fatal:', err);
  process.exit(1);
});
